---
sidebar: sidebar 
permalink: concept_determining_data_collector_acq_status.html 
summary: Estado de adquisición del recopilador de datos 
keywords: collector, acquisition, status 
---
= Determinar el estado de adquisición del recopilador de datos
:allow-uri-read: 


[role="lead"]
Debido a que los recopiladores de datos son la fuente principal de información para Cloud Insights, es imperativo asegurarse de que permanecen en estado en ejecución.

El estado del recopilador de datos se muestra en la esquina superior derecha de cualquier página de activos como el mensaje "adquirido hace N minutos", donde N indica el tiempo de adquisición más reciente de los recopiladores de datos del activo. También se muestra la fecha y hora de adquisición.

Al hacer clic en el mensaje se muestra una tabla con el nombre del recopilador de datos, el estado y la última adquisición correcta. Si ha iniciado sesión como administrador, al hacer clic en el enlace del nombre del recopilador de datos de la tabla, se le llevará a la página de detalles de ese recopilador de datos.
