---
sidebar: sidebar 
permalink: concept-performance.html 
keywords: performance, technical report, TR, workload, cpu 
summary: Es posible revisar los resultados de rendimiento con el fin de ayudarle a decidir qué cargas de trabajo son las adecuadas para Cloud Volumes ONTAP. 
---
= Rendimiento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible revisar los resultados de rendimiento con el fin de ayudarle a decidir qué cargas de trabajo son las adecuadas para Cloud Volumes ONTAP.



== Informes técnicos sobre rendimiento

ifdef::aws[]

* Cloud Volumes ONTAP para AWS
+
link:https://www.netapp.com/pdf.html?item=/media/9088-tr4383pdf.pdf["Informe técnico de NetApp 4383: Caracterización del rendimiento de Cloud Volumes ONTAP en Amazon Web Services con cargas de trabajo de las aplicaciones"^]



endif::aws[]

ifdef::azure[]

* Cloud Volumes ONTAP para Microsoft Azure
+
link:https://www.netapp.com/pdf.html?item=/media/9089-tr-4671pdf.pdf["Informe técnico de NetApp 4671: Caracterización del rendimiento de Cloud Volumes ONTAP en Azure con cargas de trabajo de aplicaciones"^]



endif::azure[]

ifdef::gcp[]

* Cloud Volumes ONTAP para Google Cloud
+
link:https://www.netapp.com/pdf.html?item=/media/9090-tr4816pdf.pdf["Informe técnico de NetApp 4816: Caracterización del rendimiento de Cloud Volumes ONTAP para Google Cloud"^]



endif::gcp[]



== Rendimiento de CPU

Los nodos de Cloud Volumes ONTAP se muestran como un gran uso (más del 90 %) de las herramientas de supervisión de su proveedor de cloud. Esto se debe a que ONTAP reserva todas las vCPU presentadas al equipo virtual para que estén disponibles cuando sea necesario.

Para obtener ayuda, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Monitoring_CPU_utilization_before_an_ONTAP_upgrade["Artículo de la base de conocimientos de NetApp acerca de cómo supervisar la utilización de CPU de ONTAP mediante la CLI"^]
