---
sidebar: sidebar 
permalink: concept-client-protocols.html 
keywords: client protocols, client version, smb version, nfs version, protocol versions, s3, smb, nfs, iscsi, cifs 
summary: Cloud Volumes ONTAP admite los protocolos de cliente iSCSI, NFS, SMB, NVMe-TCP y S3. 
---
= Protocolos de cliente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP admite los protocolos de cliente iSCSI, NFS, SMB, NVMe-TCP y S3.



== ISCSI

ISCSI es un protocolo de bloques que puede ejecutarse en redes Ethernet estándar. La mayoría de los sistemas operativos de clientes ofrecen un iniciador de software que funciona sobre un puerto Ethernet estándar.



== NFS

NFS es el protocolo tradicional de acceso a archivos para sistemas UNIX y LINUX. Los clientes pueden acceder a los archivos de volúmenes de ONTAP mediante los protocolos NFSv3, NFSv4 y NFSv4.1. Puede controlar el acceso a archivos mediante permisos de estilo UNIX, permisos de estilo NTFS o una combinación de ambos.

Los clientes pueden acceder a los mismos archivos utilizando los protocolos NFS y SMB.



== SMB

SMB es el protocolo tradicional de acceso a archivos para sistemas Windows. Los clientes pueden acceder a los archivos de los volúmenes ONTAP mediante los protocolos SMB 2.0, SMB 2.1, SMB 3.0 y SMB 3.1.1. Al igual que con NFS, se admite una combinación de estilos de permisos.



== S3

Cloud Volumes ONTAP es compatible con S3 como opción del almacenamiento de escalado horizontal. La compatibilidad con el protocolo S3 le permite configurar el acceso de clientes S3 a los objetos contenidos en un bloque de una máquina virtual de almacenamiento (SVM).

link:https://docs.netapp.com/us-en/ontap/s3-multiprotocol/index.html#how-s3-multiprotocol-works["Descubra cómo funciona el protocolo de S3"^].
link:https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["Aprenda a configurar y gestionar los servicios de almacenamiento de objetos S3 en ONTAP"^].



== NVMe-TCP

NVMe-TCP es compatible con los proveedores de cloud si utiliza Cloud Volumes ONTAP versión 9.12.1 o posterior. BlueXP no ofrece funcionalidades de gestión para NVMe-TCP.

Para obtener más información sobre cómo configurar NVMe mediante ONTAP, consulte https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-nvme-task.html["Configure una máquina virtual de almacenamiento para NVMe"^].
