---
sidebar: sidebar 
permalink: concept-active-iq.html 
keywords: autosupport, active iq, digital advisor, active iq digital advisor, telemetry 
summary: El componente AutoSupport de ONTAP recopila telemetría y la envía para su análisis. El asesor digital de Active IQ analiza los datos de AutoSupport y ofrece optimización y atención proactivas. Utilizando la inteligencia artificial, Active IQ puede identificar problemas potenciales y ayudarle a resolverlos antes de que afecten a su negocio. 
---
= Asesor digital AutoSupport y Active IQ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El componente AutoSupport de ONTAP recopila telemetría y la envía para su análisis. El asesor digital de Active IQ analiza los datos de AutoSupport y ofrece optimización y atención proactivas. Utilizando la inteligencia artificial, Active IQ puede identificar problemas potenciales y ayudarle a resolverlos antes de que afecten a su negocio. Cambio para prueba de transición.

Cambio para localización. Active docbot y pruebe la visualización de loc. Prueba de desactivación de docbot. Volver a probar la actualización de rubí por tercera vez. Prueba Ver traducción de etiquetas de todos los resultados.

Active IQ le permite optimizar su infraestructura de datos en el cloud híbrido global mediante la entrega de análisis predictivos aplicables y soporte proactivo a través de un portal basado en cloud y una aplicación para dispositivos móviles. En Active IQ, todos los clientes de NetApp con un contrato activo de SupportEdge disponen de información y recomendaciones basadas en los datos (las funciones varían según el producto y el nivel de soporte).

Estas son algunas cosas que puede hacer con Active IQ:

* Planificación de actualizaciones.
+
Active IQ identifica los problemas en su entorno que se pueden resolver actualizando a una versión más reciente de ONTAP y el componente Upgrade Advisor le ayuda a planificar una actualización correcta.

* Ver el bienestar del sistema.
+
Su consola de Active IQ informa de cualquier problema con el bienestar y le ayuda a corregir estos problemas. Supervise la capacidad del sistema para asegurarse de que nunca se queda sin espacio de almacenamiento. Vea los casos de soporte de su sistema.

* Gestión del rendimiento.
+
Active IQ muestra el rendimiento del sistema durante un período más largo de lo que se puede ver en System Manager de ONTAP. Identifique problemas de configuración y del sistema que afectan a su rendimiento.
Optimice la eficiencia. Consulte los criterios de medición de la eficiencia del almacenamiento e identifique formas de almacenar más datos en menos espacio.

* Ver el inventario y la configuración.
+
Active IQ muestra información completa sobre la configuración de inventario y software y hardware. Vea cuándo caducan los contratos de servicio y renueve su soporte para asegurarse de que sigue siendo compatible.



.Información relacionada
* https://docs.netapp.com/us-en/active-iq/["Documentación de NetApp: Asesor digital de Active IQ"^]
* https://aiq.netapp.com/custom-dashboard/search["Inicie Active IQ"^]
* https://www.netapp.com/us/services/support-edge.aspx["Servicios de SupportEdge"^]

