---
sidebar: sidebar 
permalink: concept_import_from_dashboard_gallery.html 
summary: Puede importar paneles recomendados para ayudarle a responder preguntas de información empresarial. 
keywords: dashboard, gallery, import 
---
= Importando desde la galería de paneles
:allow-uri-read: 


[role="lead"]
Cloud Insights ofrece una serie de paneles recomendados para proporcionar información empresarial sobre los datos. Cada panel contiene widgets diseñados para ayudar a responder a una pregunta concreta o resolver un problema concreto relacionado con los datos que se recopilan actualmente en su entorno.

Para importar un panel desde la galería, haga lo siguiente:

. Seleccione *Panel > Mostrar todos los paneles*
. Haga clic en *+from Gallery*
+
Aparecerá una lista de *Paneles recomendados*. Cada panel tiene un nombre con una pregunta concreta que el panel puede ayudarle a resolver. Las consolas están disponibles para ofrecer respuesta a las preguntas sobre diferentes tipos de objetos, incluidos AWS, NetApp, almacenamiento, VMware, y otros

. Seleccione uno o más paneles de la lista y haga clic en *Agregar paneles*. Estos paneles ahora aparecen en su lista de paneles.


Además de los paneles recomendados, también puede elegir importar *Paneles adicionales* que no sean relevantes para los datos actuales. Por ejemplo, si no tiene actualmente ningún recopilador de datos de almacenamiento instalado pero está planeando configurar algunos en el futuro, puede que decida importar los paneles relevantes para el almacenamiento. Estos paneles estarán disponibles para su visualización, pero es posible que no muestren ningún dato relevante hasta que se configure al menos un recopilador de datos de almacenamiento.
