---
sidebar: sidebar 
permalink: concept_asset_page_overview.html 
summary: Las páginas de activos se pueden mostrar para la mayoría de los tipos de objeto. 
keywords: asset page, objects, landing page, Virtual machine, VM, Storage Virtual Machine, SVM, Volume, Internal volume, Host, Hypervisor, pool, Storage, Datastore, Application, node, Qtree, Disk, VMDK, Port, Switch, Fabric 
---
= Descripción general de la página de activos
:allow-uri-read: 


[role="lead"]
Las páginas de activos resumen el estado actual de un activo y contienen vínculos a información adicional sobre el activo y sus activos relacionados.



== Tipos de páginas de activos

Cloud Insights proporciona páginas de activos para los siguientes activos:

* Máquina virtual
* Máquina virtual de almacenamiento (SVM)
* Volumen
* Volumen interno
* Host (incluido hipervisor)
* Del banco de almacenamiento
* Reducida
* Almacén de datos
* Cliente más
* Nodo de almacenamiento
* Qtree
* Disco
* VMDK
* Puerto
* Conmutador
* Estructura




== Cambio del intervalo de tiempo de los datos mostrados

De forma predeterminada, una página de activos muestra las últimas 24 horas de datos; sin embargo, puede cambiar el segmento de datos que se muestra seleccionando otro intervalo de tiempo fijo o un intervalo de tiempo personalizado para ver menos o más datos.

Puede cambiar el segmento de tiempo de los datos mostrados mediante una opción que se encuentra en cada página de activos, independientemente del tipo de activo. Para cambiar el intervalo de tiempo, haga clic en el intervalo de tiempo que se muestra en la barra superior y elija entre los siguientes segmentos de tiempo:

* Últimos 15 minutos
* Últimos 30 minutos
* Últimos 60 minutos
* Últimas 2 horas
* Últimas 3 horas (este es el valor predeterminado)
* Últimas 6 horas
* Últimas 12 horas
* Últimas 24 horas
* Últimos 2 días
* Últimos 3 días
* Últimos 7 días
* Últimos 30 días
* Intervalo de tiempo personalizado


El intervalo de tiempo personalizado le permite seleccionar hasta 31 días consecutivos. También puede establecer la hora de inicio y la hora de finalización del día para este intervalo. La hora de inicio predeterminada es 12:00 AM del primer día seleccionado y la hora de finalización predeterminada es 11:59 PM del último día seleccionado. Al hacer clic en aplicar se aplicará el intervalo de tiempo personalizado a la página del activo.



== Agregar widgets personalizados

Puede añadir sus propios widgets a cualquier página de activo. Los widgets que agregue aparecerán en las páginas de activos de todos los objetos de ese tipo. Por ejemplo, si se añade un widget personalizado a una página de activos de almacenamiento, aparecerá el widget correspondiente en las páginas de activos de todos los activos de almacenamiento.
