---
sidebar: sidebar 
permalink: cs_restrict_user_access.html 
keywords: alert, snapshot,  attack 
summary: Con Cloud Secure, puede restringir el acceso de los usuarios en caso de sospecha de sabotaje 
---
= Restricción del acceso del usuario
:allow-uri-read: 


[role="lead"]
Una vez detectado un ataque, Cloud Secure puede detener el ataque restringiendo el acceso del usuario al sistema de archivos. El acceso se puede restringir automáticamente mediante Directivas de respuesta automatizadas o manualmente desde las páginas de alerta o detalles del usuario.

Al restringir el acceso del usuario, debe definir el tipo de límite de acceso (bloque o solo lectura) y el período de tiempo. Una vez finalizado el período de tiempo seleccionado, el acceso del usuario se restaura automáticamente.

La restricción de acceso es compatible tanto con los protocolos SMB como NFS.

La restricción ocurre a través de la dirección IP de los equipos host, lo que significa que los equipos desde los que el usuario ha accedido al almacenamiento. Esas direcciones IP de la máquina no podrán acceder a ninguna de las máquinas virtuales de almacenamiento (SVM) supervisadas por Cloud Secure.

Por ejemplo, supongamos que Cloud Secure gestiona 10 SVM y que la Política de respuesta automática está configurada para cuatro de ellas. Si el ataque se origina en una de las cuatro SVM, se restringirá el acceso del usuario a las 10 SVM. Se sigue utilizando una snapshot en la SVM de origen.

Si hay cuatro SVM con una SVM configurada para CIFS, una configurada para NFS y los dos restantes configurados para NFS y CIFS, todas las SVM se bloquearán si el ataque se origina en cualquiera de las cuatro SVM.



=== Requisitos previos para la restricción de acceso del usuario

Los clientes deben configurar políticas de exportación para SMB y NFS para que esta función funcione. Siga los pasos que se indican a continuación si NFS y SMB están configurados en el recopilador de origen de datos.

Para NFS, las políticas de exportación se configuran de forma predeterminada. De forma predeterminada, se crea una política de exportación cuando se crea el servicio NFS en la SVM.

Para SMB, se deben configurar las políticas de exportación.

Si NO utiliza credenciales de clúster/svm pero utiliza un csuser, siga primero los pasos que se indican a continuación para permitir que Cloud Secure cree una regla de política de exportación personalizada.

Para csuser con credenciales de clúster, haga lo siguiente desde la línea de comandos ONTAP:

 security login role create -role csrole -cmddirname "vserver export-policy rule" -access all
Para csuser con credenciales de SVM, haga lo siguiente desde la línea de comandos de ONTAP, insertando el <vservername> correcto:

 security login role create -vserver <vservername> -role csrole -cmddirname "vserver export-policy rule" -access all
A continuación, se muestran los comandos para configurar una política de exportación predeterminada. Copie los comandos en un editor de texto y reemplace el nombre <vserver> por el nombre del Vserver. A continuación, copie cada línea de una en una y ejecútela en la consola ONTAP. Tenga en cuenta que primero debe cambiar al modo avanzado antes de ejecutar los comandos.


TIP: Esto resulta especialmente útil para ejecutar pruebas de concepto. En los equipos en los que desea probar, SMB se puede configurar como se muestra a continuación. Durante las pruebas de concepto, en los recopiladores de origen de datos, habilite únicamente el protocolo SMB/CIFS y deshabilite el protocolo NFS.

 set -privilege advanced
 cifs options modify -is-exportpolicy-enabled true -vserver <vserver>
 export-policy rule create -vserver <vserver> -policyname default -protocol cifs -clientmatch 0.0.0.0/0 -rorule any -rwrule any

NOTE: El clientmatch es una dirección específica o una subred (por ejemplo, 10.0.3.212 o 192.168.5.0/24), un nombre de host o un netgroup, como @netgroup. Si desea que una política de exportación se aplique a todas las direcciones IP4 posibles, establezca el valor de clientmatch en 0.0.0.0/0.

Para comprobar si la regla _exportpolicy_ y _exportpolicy_ se han configurado correctamente, ejecute los comandos siguientes después de ejecutar los comandos anteriores.

 cifs options show  -fields is-exportpolicy-enabled -vserver <vserver>
 export-policy show -vserver <vserver>
 export-policy rule show -policyname default -vserver <vserver>


=== ¿Cómo se habilita la función?

* En Cloud Secure, vaya a *Administración > Directivas de respuesta automatizadas > Configuración de la directiva de respuesta > limitación de acceso*.
* Establezca “Activar restringir acceso de usuario” en _Enabled_.




=== ¿Cómo configurar la restricción automática de acceso del usuario?

* Cree una nueva directiva de ataque o edite una directiva de ataque existente.
* Seleccione las SVM en las que debe supervisarse la política de ataque.
* Haga clic en la casilla de verificación “restringir el acceso al archivo IP del usuario”. La función se activará cuando se seleccione esta opción.
* En “limitar acceso de usuario”, seleccione el modo de restricción que se debe aplicar.
* En “período de tiempo”, seleccione el tiempo hasta el que se debe aplicar la restricción.
* Para probar la restricción automática, puede simular un ataque a través de un link:concept_cs_attack_simulator.html["guión simulado"].




=== ¿Cómo saber si hay usuarios restringidos en el sistema?

* En la página de listas de alertas, se mostrará un banner en la parte superior de la pantalla en caso de que se restrinja cualquier usuario.
* Al hacer clic en el banner, se abre la página “usuarios”. En que se puede ver la lista de usuarios restringidos.
* En la página “Users” (usuarios), hay una columna llamada “IP Access” (acceso IP). En esa columna, se mostrará el estado actual de restricción de usuario.




=== Restringir y administrar el acceso de los usuarios manualmente

* Puede ir a la pantalla de detalles de alerta o de usuario y, a continuación, restringir o anular la restricción manual de un usuario de esas pantallas.




=== Historial de acceso de restricción de usuario

En la página de detalles de alerta y detalles de usuario, en el panel de usuario, puede ver una auditoría del historial de limitación de acceso restringido del usuario: Tiempo, Acción (bloqueo, sólo lectura, restauración), duración, Acción realizada por, IP manuales/automáticas y afectadas.



=== ¿Cómo deshabilitar la función?

Es posible deshabilitar la función en cualquier momento. Si hay usuarios restringidos en el sistema, primero debe restaurar su acceso.

* En Cloud Secure, vaya a *Administración > Directivas de respuesta automatizadas > Configuración de la directiva de respuesta > limitación de acceso*
* Anule la selección de “Activar restringir acceso de usuario” para desactivarlo.


La operación se ocultará de todas las páginas.



=== Restaure manualmente las IP

Siga estos pasos para restaurar manualmente cualquier IP desde ONTAP si finaliza la prueba de Cloud Secure o si el agente/recopilador está inactivo.

. Enumere todas las políticas de exportación de una SVM.
+
....
contrail-qa-fas8020::> export-policy rule show -vserver <svm name>
             Policy          Rule    Access   Client                RO
Vserver      Name            Index   Protocol Match                 Rule
------------ --------------- ------  -------- --------------------- ---------
svm_s_____a default         1       nfs3,    cloudsecure_rule,     never
                                     nfs4,    10.19.12.216
                                     cifs
svm_s_____a default         4       cifs,    0.0.0.0/0             any
                                     nfs
svm_s_____a test            1       nfs3,    cloudsecure_rule,     never
                                     nfs4,    10.19.12.216
                                     cifs
svm_s_____a test            3       cifs,    0.0.0.0/0             any
                                     nfs,
                                     flexcache
4 entries were displayed.
....
. Elimine todas las reglas en todas las directivas de la SVM que tengan “cloudsecure_rule” como Client Match especificando su respectivo RuleIndex. La regla CloudSecure estará normalmente en 1.
+
 contrail-qa-fas8020::*> export-policy rule delete -vserver <svm name> -policyname * -ruleindex 1
. Asegúrese de que se ha eliminado la regla cloudsecure (paso opcional para confirmar).
+
....
contrail-qa-fas8020::*> export-policy rule show -vserver <svm name>
             Policy          Rule    Access   Client                RO
Vserver      Name            Index   Protocol Match                 Rule
------------ --------------- ------  -------- --------------------- ---------
svm_suchitra default         4       cifs,    0.0.0.0/0             any
                                     nfs
svm_suchitra test            3       cifs,    0.0.0.0/0             any
                                     nfs,
                                     flexcache
2 entries were displayed.
....




== Resolución de problemas

|===
| Problema | Pruebe esto 


| Algunos de los usuarios no se están restringiendo, aunque hay un ataque. | 1. Asegúrese de que el recopilador de datos y el agente de las SVM se encuentran en el estado _running_. Cloud Secure no podrá enviar comandos si el recopilador de datos y el agente están detenidos. 2. Esto se debe a que el usuario puede haber accedido al almacenamiento desde una máquina con una IP nueva que no se ha usado antes. La restricción ocurre mediante la dirección IP del host a través del cual el usuario accede al almacenamiento. Compruebe en la interfaz de usuario (Detalles de alerta > Historial de limitación de acceso para este usuario > IP afectadas) la lista de direcciones IP restringidas. Si el usuario accede al almacenamiento desde un host con una IP diferente a las IP restringidas, el usuario podrá seguir accediendo al almacenamiento a través de la IP sin restricciones. Si el usuario intenta acceder desde los hosts cuyas IP están restringidas, no se podrá acceder al almacenamiento. 


| Al hacer clic manualmente en restringir acceso se proporciona “las direcciones IP de este usuario ya han sido restringidas”. | La dirección IP que se va a restringir ya está restringida a otro usuario. 


| Se produce un error en la restricción de acceso con la advertencia "el uso de la política de exportación para el protocolo SMB está deshabilitado para la SVM. Habilitar el uso de la política de exportación para utilizar la función restringir acceso de usuario” | Asegúrese de que la opción -is-exportpolicy-enabled es verdadera para el Vserver como se menciona en los requisitos previos. 
|===