---
sidebar: sidebar 
permalink: forensic_alert_detail.html 
keywords: alert, Critical, Warning, Low, alert detail Synopsis, Time range, Start time, End time, user 
summary: detalles de alertas 
---
= Detalles de alertas
:allow-uri-read: 


[role="lead"]
Al hacer clic en la sinopsis de una alerta, se abre la página con información detallada del usuario y de la alerta que han generado.



== La página Alert Details muestra al usuario

Alert Details proporciona información sobre la alerta seleccionada en la página Alertas.

* La gravedad de la alerta
* El usuario que elevó la alerta y el tipo de alerta:
+
** Acceso anormal por el usuario
** Acceso anormal por comunidad
** Acceso anormal por el usuario en la comunidad
** Usuario se unió a muchas comunidades


* La fecha y la hora en que se detectó la alerta
* Las medidas adoptadas
+
** En cuarentena
** Otros
** Otros


* El estado de la alerta
+
** Nuevo
** En curso
** Desestimada
** Resuelto


* Cambio de la tasa de actividad del usuario
+
** Actividades típicas por hora
** Actividades por hora cuando se elevó la alerta.
** Porcentaje de cambio de tasa que provocó la alerta.


* Un gráfico que muestra la tasa media histórica y la tasa de actividad que dio lugar a la alerta.




=== Usuario relacionado

* Nombre de usuario y cargo
* Departamento
* Correo electrónico con un enlace a la dirección de correo electrónico
* Gerente
* Teléfono
* Ubicación




=== Actividad

Muestra la actividad del usuario durante los últimos 7 días y la última ubicación desde la que se ha accedido.

* Actividades:
+
** Lea
** Otros
** Cree


* Número total de alertas de los últimos siete días.
* Número total de actividades de los últimos 7 días.


Haga clic en *Ver detalle de actividad* para acceder a link:forensic_activity_history["Historial de actividades"] del usuario que se está examinando.
