---
sidebar: sidebar 
permalink: reference_legal_notices.html 
keywords: copyrights, notice, trademarks, patents, privacy, open source 
summary: Los avisos legales proporcionan acceso a las declaraciones de copyright, marcas comerciales, patentes y mucho más. 
---
= Avisos legales
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los avisos legales proporcionan acceso a las declaraciones de copyright, marcas comerciales, patentes y mucho más.



== Derechos de autor

http://www.netapp.com/us/legal/copyright.aspx[]



== Marcas comerciales

NETAPP, el logotipo de NETAPP y las marcas enumeradas en la página de marcas comerciales de NetApp son marcas comerciales de NetApp, Inc. Los demás nombres de empresas y productos son marcas comerciales de sus respectivos propietarios.

http://www.netapp.com/us/legal/netapptmlist.aspx[]



== Estadounidenses

Puede encontrar una lista actual de las patentes propiedad de NetApp en:

https://www.netapp.com/us/media/patents-page.pdf[]



== Política de privacidad

https://www.netapp.com/us/legal/privacypolicy/index.aspx[]



== Código abierto

Los archivos de notificación proporcionan información sobre los derechos de autor y las licencias de terceros que se utilizan en software de NetApp.

* link:media/Notice_Cloud_Insights-2021.05.18.pdf["Aviso sobre Cloud Insights"]

