---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, flexgroup, ontap s3, s3 configuration, svm dr, svm disaster recovery, disaster recovery, storage vm dr, BlueXP, cloud manager 
summary: Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente. 
---
= Limitaciones conocidas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente.

Estas limitaciones son específicas de la gestión de Cloud Volumes ONTAP en BlueXP. Para ver las limitaciones con el propio software de Cloud Volumes ONTAP, https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limitations.html["Vaya a las notas de la versión de Cloud Volumes ONTAP"^]



== BlueXP no es compatible con la creación de volúmenes de FlexGroup

Aunque Cloud Volumes ONTAP es compatible con FlexGroup Volumes, BlueXP no admite actualmente la creación de volúmenes de FlexGroup. Si crea un volumen de FlexGroup desde System Manager o desde la CLI, debe configurar el modo de gestión de capacidad de BlueXP en Manual. El modo automático puede no funcionar correctamente con volúmenes de FlexGroup.


NOTE: La capacidad para crear volúmenes de FlexGroup en BlueXP está prevista para una futura versión.



== BlueXP no es compatible con S3 con Cloud Volumes ONTAP

Aunque Cloud Volumes ONTAP admite S3 como opción de almacenamiento de escalado horizontal, BlueXP no proporciona ninguna funcionalidad de gestión para esta función. Usar la CLI es la práctica recomendada para configurar el acceso del cliente S3 desde Cloud Volumes ONTAP. Para obtener más información, consulte http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["Guía completa de configuración de S3"^].

link:concept-client-protocols.html["Obtenga más información sobre la compatibilidad de Cloud Volumes ONTAP con S3 y otros protocolos de cliente"].



== BlueXP no admite recuperación ante desastres para equipos virtuales de almacenamiento

BlueXP no ofrece compatibilidad con ninguna configuración u orquestación para la recuperación ante desastres de máquinas virtuales de almacenamiento (SVM). Se debe usar System Manager o la CLI.

link:task-manage-svm-dr.html["Obtenga más información sobre la recuperación ante desastres de SVM"].
