---
sidebar: sidebar 
permalink: reporting_creating_custom_reports.html 
summary: 'Uso de herramientas de creación de informes para crear informes personalizados ("ad-hoc")' 
keywords: reporting, cognos, data warehouse, dwh, ad-hoc, custom 
---
= Creación de informes personalizados
:allow-uri-read: 


[role="lead"]
Puede utilizar las herramientas de creación de informes para crear informes personalizados. Después de crear informes, puede guardarlos y ejecutarlos en un horario normal. Los resultados de los informes se pueden enviar automáticamente por correo electrónico a usted mismo y a otros.


NOTE: La función Reporting se encuentra disponible en Cloud Insights link:concept_subscribing_to_cloud_insights.html["Edición Premium"].

Los ejemplos de esta sección muestran el siguiente proceso, que se puede utilizar para cualquiera de los modelos de datos de informes de Cloud Insights:

* Identificar una pregunta que se va a responder con un informe
* Determinar los datos necesarios para respaldar los resultados
* Selección de elementos de datos para el informe


Antes de diseñar su informe personalizado, debe completar algunas tareas de requisitos previos. Si no los completa, los informes podrían ser inexactos o incompletos.

Por ejemplo, si no finaliza el proceso de identificación del dispositivo, los informes de capacidad no serán precisos. O bien, si no termina de establecer anotaciones (como niveles, unidades de negocio y centros de datos), es posible que sus informes personalizados no informen de forma precisa los datos en todo su dominio o que muestren "N/A" para algunos puntos de datos.

Antes de diseñar los informes, lleve a cabo las tareas siguientes:

* Configurar todo link:task_configure_data_collectors.html["recopiladores de datos"] regularmente.
* Introducir anotaciones (como niveles, centros de datos y unidades de negocio) en dispositivos y recursos del entorno. Es beneficioso que las anotaciones sean estables antes de generar informes, ya que el sistema de informes de Cloud Insights recopila información histórica.




=== Proceso de creación de informes

El proceso de creación de informes personalizados (también llamados "ad hoc") implica varias tareas:

* Planifique los resultados de su informe.
* Identifique los datos que respaldan sus resultados.
* Seleccione el modelo de datos (por ejemplo, modelo de datos de pago por uso, modelo de datos de inventario, etc.) que contiene los datos.
* Seleccione los elementos de datos para el informe.
* Si lo desea, puede aplicar formato, ordenar y filtrar los resultados del informe.




==== Planificación de los resultados de su informe personalizado

Antes de abrir las herramientas de creación de informes, es posible que desee planificar los resultados deseados en el informe. Las herramientas de creación de informes permiten crear informes con facilidad y es posible que no necesite mucha planificación; sin embargo, es buena idea tener una idea del solicitante del informe sobre los requisitos del informe.

* Identifique la pregunta exacta que desea responder. Por ejemplo:
+
** ¿Cuánta capacidad me queda?
** ¿Cuáles son los costos de pago por uso por unidad de negocios?
** ¿Qué capacidad tiene el nivel para garantizar que las unidades de negocio estén alineadas en el nivel de almacenamiento adecuado?
** ¿Cómo puedo prever los requisitos de energía y refrigeración? (Añada metadatos personalizados añadiendo anotaciones a los recursos).


* Identifique los elementos de datos que necesita para respaldar la respuesta.
* Identifique las relaciones entre los datos que desea ver en la respuesta. No incluya relaciones ilógicas en su pregunta, por ejemplo, “Quiero ver los puertos que se relacionan con la capacidad”.
* Identificar los cálculos necesarios en los datos.
* Determine qué tipos de filtrado son necesarios para limitar los resultados.
* Determinar si necesita utilizar datos actuales o históricos.
* Determine si necesita establecer privilegios de acceso en los informes para limitar los datos a audiencias específicas.
* Identificar cómo se distribuirá el informe. Por ejemplo, ¿debería enviarse por correo electrónico en un programa determinado o incluirse en el área de carpeta de contenido del equipo?
* Determinar quién mantendrá el informe. Esto puede afectar a la complejidad del diseño.
* Crear una maquinación del informe.




==== Sugerencias para diseñar informes

Es posible que varias sugerencias sean útiles cuando se diseñan informes.

* Determinar si necesita utilizar datos actuales o históricos.
+
La mayoría de los informes solo deben generar informes sobre los datos más recientes disponibles en Cloud Insights.

* La generación de informes de Cloud Insights proporciona información histórica sobre la capacidad y el rendimiento, pero no sobre el inventario.
* Todo el mundo ve todos los datos; sin embargo, es posible que tenga que limitar los datos a audiencias específicas.
+
Para segmentar la información de diferentes usuarios, puede crear informes y establecer permisos de acceso en ellos.





== Modelos de datos de generación de informes

Cloud Insights incluye varios modelos de datos a partir de los cuales se pueden seleccionar informes predefinidos o crear un informe personalizado.

Cada modelo de datos contiene un simple data Mart y un Data Mart avanzado:

* El sencillo Data Mart proporciona un acceso rápido a los elementos de datos utilizados con más frecuencia e incluye sólo la última instantánea de los datos del almacén de datos; no incluye datos históricos.
* El Data Mart avanzado proporciona todos los valores y detalles disponibles desde el simple data Mart e incluye acceso a valores de datos históricos.




=== Modelo de datos de capacidad

Le permite responder preguntas acerca de la capacidad de almacenamiento, el uso del sistema de archivos, la capacidad de volumen interno, la capacidad del puerto, la capacidad para qtrees, Y la capacidad de las máquinas virtuales (VM). El modelo de datos de capacidad es un contenedor para varios modelos de datos de capacidad. Puede crear informes que contesten varios tipos de preguntas mediante este modelo de datos:



=== Modelo de datos con capacidad de almacenamiento y pool de almacenamiento

Le permite responder preguntas sobre la planificación de recursos de la capacidad de almacenamiento, incluidos los pools de almacenamiento y almacenamiento, e incluye datos de pools de almacenamiento físico y virtual. Este sencillo modelo de datos puede ayudarle a responder a preguntas relacionadas con la capacidad sobre el suelo y el uso de la capacidad de los pools de almacenamiento por nivel y centro de datos con el tiempo. Si es el nuevo modelo de informes de capacidad, debe empezar por este modelo de datos, ya que es un modelo de datos más sencillo y objetivo. Con este modelo de datos, puede responder preguntas similares a las siguientes:

* ¿Cuál es la fecha prevista para alcanzar el umbral de capacidad del 80% del almacenamiento físico?
* ¿Cuál es la capacidad de almacenamiento físico de una cabina para un nivel determinado?
* ¿Qué capacidad de almacenamiento tienen el fabricante, la familia y el centro de datos?
* ¿Cuál es la tendencia de utilización de almacenamiento en un arreglo para todos los niveles?
* ¿Cuáles son mis 10 sistemas de almacenamiento principales con un mayor aprovechamiento?
* ¿Cuál es la tendencia de uso del almacenamiento de los pools de almacenamiento?
* ¿Qué capacidad ya está asignada?
* ¿Qué capacidad está disponible para la asignación?




=== Modelo de datos de utilización del sistema de ficheros

Este modelo de datos ofrece visibilidad sobre el uso de la capacidad por parte de los hosts a nivel de sistema de archivos. Los administradores pueden determinar la capacidad asignada y utilizada por sistema de ficheros, determinar el tipo de sistema de ficheros e identificar las estadísticas de tendencias por tipo de sistema de ficheros. Puede responder a las siguientes preguntas utilizando este modelo de datos:

* ¿Cuál es el tamaño del sistema de archivos?
* ¿Dónde se almacenan los datos y cómo se accede a ellos, por ejemplo, local o SAN?
* ¿Cuáles son las tendencias históricas de la capacidad del sistema de archivos? Entonces, en base a esto, ¿qué podemos prever para las necesidades futuras?




=== Modelo de datos con capacidad de volumen interno

Permite responder a preguntas sobre la capacidad interna de volumen utilizado, la capacidad asignada y el uso de la capacidad a lo largo del tiempo:

* ¿Qué volúmenes internos tienen un aprovechamiento superior a un umbral predefinido?
* ¿Qué volúmenes internos corren el peligro de quedarse sin capacidad según una tendencia? 8 ¿Cuál es la capacidad utilizada respecto a la capacidad asignada en nuestros volúmenes internos?




=== Modelo de datos de capacidad del puerto

Le permite responder preguntas acerca de la conectividad de los puertos del switch, el estado de los puertos y la velocidad de los puertos a lo largo del tiempo. Puede responder a preguntas similares a las siguientes para ayudarle a planificar la compra de switches nuevos: ¿Cómo puedo crear una previsión de consumo de puertos que predice la disponibilidad de los recursos (puertos) (según el centro de datos, el proveedor de switches y la velocidad de puertos)?

* ¿Qué puertos pueden quedarse sin capacidad y proporcionar velocidad de datos, centro de datos, proveedor y número de puertos de host y almacenamiento?
* ¿Cuáles son las tendencias de capacidad de los puertos del switch con el tiempo?
* ¿Cuáles son las velocidades de puerto?
* ¿Qué tipo de capacidad de puerto es necesaria y qué organización está a punto de quedarse sin un determinado tipo de puerto o proveedor?
* ¿Cuál es el momento adecuado para adquirir esa capacidad y hacerla disponible?




=== Modelo de datos de capacidad Qtree

Permite tendencia al uso de qtrees (con datos como usar o la capacidad asignada) a lo largo del tiempo. Puede ver la información por diferentes dimensiones; por ejemplo, por entidad de negocio, aplicación, nivel y nivel de servicio. Puede responder a las siguientes preguntas utilizando este modelo de datos:

* ¿Cuál es la capacidad usada para qtrees frente a los límites establecidos por aplicación o entidad empresarial?
* ¿Cuáles son las tendencias de nuestra capacidad libre y usada para que podamos planificar la capacidad?
* ¿Qué entidades de negocio utilizan más capacidad?
* ¿Qué aplicaciones consumen la mayor capacidad?




=== Modelo de datos de capacidad de las máquinas virtuales

Le permite informar sobre el entorno virtual y el uso de su capacidad. Este modelo de datos le permite informar sobre los cambios en el uso de la capacidad a lo largo del tiempo en equipos virtuales y almacenes de datos. El modelo de datos también proporciona datos de pago por uso de equipos virtuales y thin provisioning.

* ¿Cómo puedo determinar el pago por uso de la capacidad en función de la capacidad aprovisionada para los equipos virtuales y los almacenes de datos?
* ¿Qué capacidad no utilizan los equipos virtuales y qué parte de los que no se utilizan está libre, huérfana u otra?
* ¿Qué necesitamos comprar en función de las tendencias de consumo?
* ¿Cuáles son los ahorros obtenidos con la eficiencia del almacenamiento gracias a las tecnologías de thin provisioning y deduplicación del almacenamiento?


Las capacidades del modelo de datos de capacidad de máquinas virtuales están tomadas de discos virtuales (VMDK). Esto significa que el tamaño aprovisionado de una máquina virtual utilizando el modelo de datos de capacidad de la máquina virtual es el tamaño de sus discos virtuales. Esto es diferente de la capacidad aprovisionada en la vista de equipos virtuales de Cloud Insights, que muestra el tamaño aprovisionado para los propios equipos virtuales.



=== Modelo de datos de capacidad de volumen

Le permite analizar todos los aspectos de los volúmenes de su entorno y organizar los datos por proveedor, modelo, nivel, nivel de servicio y centro de datos.

Es posible ver la capacidad relacionada con volúmenes huérfanos, volúmenes sin usar y volúmenes de protección (que se usan para la replicación). También puede ver diferentes tecnologías de volúmenes (iSCSI o FC) y comparar volúmenes virtuales con volúmenes no virtuales para problemas de virtualización de cabinas.

Con este modelo de datos, puede responder preguntas similares a las siguientes:

* ¿Qué volúmenes tienen un aprovechamiento superior a un umbral predefinido?
* ¿Cuál es la tendencia de la capacidad de volumen huérfana en mi centro de datos?
* ¿Qué cantidad de capacidad de mi centro de datos está virtualizada o con thin provisioning?
* ¿Qué cantidad de capacidad de mi centro de datos debe reservarse para la replicación?




=== Modelo de datos de pago por uso

Le permite responder preguntas sobre la capacidad utilizada y la capacidad asignada de los recursos de almacenamiento (volúmenes, volúmenes internos y qtrees). Este modelo de datos proporciona información de pago por uso y responsabilidad de la capacidad de almacenamiento por hosts, aplicaciones y entidades de negocio, e incluye datos actuales e históricos. Los datos de los informes se pueden clasificar por nivel de servicio y nivel de almacenamiento.

Puede utilizar este modelo de datos para generar informes de pago por uso al encontrar la cantidad de capacidad que usa una entidad de negocio. Este modelo de datos le permite crear informes unificados de varios protocolos (incluidos NAS, SAN, FC e iSCSI).

* Para el almacenamiento sin volúmenes internos, los informes de pago por uso muestran el pago por uso por volúmenes.
* Para almacenamiento con volúmenes internos:
+
** Si se asignan entidades de negocio a volúmenes, los informes de pago por uso muestran el pago por uso por volúmenes.
** Si las entidades de negocio no están asignadas a volúmenes pero están asignadas a qtrees, los informes de pago por uso muestran un pago por uso por qtrees.
** Si las entidades de negocio no están asignadas a volúmenes y no están asignadas a qtrees, los informes de pago por uso muestran el volumen interno.
** La decisión de si se muestra el pago por uso por volumen, qtree o volumen interno se realiza por cada volumen interno, por lo que es posible que diferentes volúmenes internos del mismo pool de almacenamiento muestren el pago por uso en distintos niveles.




Los hechos de la capacidad se purgan después de un intervalo de tiempo predeterminado. Para obtener más información, consulte procesos de almacén de datos.

Los informes que utilizan el modelo de datos de pago por uso pueden mostrar diferentes valores que los informes que utilizan el modelo de datos capacidad de almacenamiento.

* Para las cabinas de almacenamiento que no son sistemas de almacenamiento de NetApp, los datos de ambos modelos de datos son los mismos.
* Para los sistemas de almacenamiento de NetApp y Celerra, el modelo de datos de pago por uso utiliza una sola capa (de volúmenes, volúmenes internos o qtrees) para basar sus cargos, mientras que el modelo de datos de capacidad de almacenamiento utiliza varias capas (de volúmenes y volúmenes internos) para basar sus cargos.




=== Modelo de datos de inventario

Le permite responder a preguntas acerca de los recursos de inventario, incluidos hosts, sistemas de almacenamiento, switches, discos, cintas, qtrees, cuotas, equipos virtuales y servidores, y dispositivos genéricos. El modelo de datos Inventory incluye varios submarts que permiten ver información acerca de las replicaciones, rutas FC, rutas iSCSI, rutas NFS e infracciones. El modelo de datos de inventario no incluye datos históricos. Preguntas que puede responder con estos datos

* ¿Qué activos tengo y dónde están?
* ¿Quién utiliza los activos?
* ¿Qué tipos de dispositivos tengo y cuáles son los componentes de esos dispositivos?
* ¿Cuántos hosts por SO tengo y cuántos puertos existen en esos hosts?
* ¿Qué cabinas de almacenamiento existen por proveedor en cada centro de datos?
* ¿Cuántos switches por proveedor tengo en cada centro de datos?
* ¿Cuántos puertos no tienen licencia?
* ¿Qué cintas de proveedores estamos usando y cuántos puertos hay en cada cinta?¿todos los dispositivos genéricos identificados antes de empezar a trabajar en los informes?
* ¿Cuáles son las rutas entre los hosts y los volúmenes o las cintas de almacenamiento?
* ¿Cuáles son los caminos entre los dispositivos genéricos y los volúmenes o las cintas de almacenamiento?
* ¿Cuántas infracciones de cada tipo tengo por centro de datos?
* Para cada volumen replicado, ¿cuáles son los volúmenes de origen y de destino?
* ¿Tengo alguna incompatibilidades del firmware o coincidencia incorrecta de velocidad del puerto entre switches y HBA del host Fibre Channel?




=== Modelo de datos de rendimiento

Le permite responder preguntas sobre el rendimiento de volúmenes, volúmenes de aplicaciones, volúmenes internos, switches, aplicaciones, Máquinas virtuales, VMDK, ESX frente a nodos de máquinas virtuales, hosts y aplicaciones. Con este modelo de datos, puede crear informes que respondan a varios tipos de preguntas de gestión del rendimiento:

* ¿Qué volúmenes o volúmenes internos no se han utilizado o no se ha accedido a ellos durante un periodo específico?
* ¿Podemos determinar cualquier configuración incorrecta posible para el almacenamiento de una aplicación (sin utilizar)?
* ¿Cuál fue el patrón de comportamiento de acceso general de una aplicación?
* ¿Se asignan los volúmenes por niveles de forma adecuada para una aplicación determinada?
* ¿Podríamos utilizar almacenamiento más económico para una aplicación que se ejecute actualmente sin que ello afecte al rendimiento de la aplicación?
* ¿Cuáles son las aplicaciones que producen más acceso al almacenamiento configurado actualmente?


Cuando utilice las tablas de rendimiento del conmutador, puede obtener la siguiente información:

* ¿Se equilibra mi tráfico de host a través de puertos conectados?
* ¿Qué interruptores o puertos están mostrando un gran número de errores?
* ¿Cuáles son los switches más utilizados en función del rendimiento de los puertos?
* ¿Cuáles son los switches infrautilizados en función del rendimiento de los puertos?
* ¿Cuál es el rendimiento de la tendencia del host en función del rendimiento de los puertos?
* ¿Cuál es la utilización del rendimiento de los últimos X días de un host, sistema de almacenamiento, cinta o switch específico?
* ¿Qué dispositivos producen tráfico en un conmutador específico (por ejemplo, qué dispositivos son responsables del uso de un conmutador altamente utilizado)?
* ¿Cuál es el rendimiento de una unidad de negocio específica en nuestro entorno?


Cuando se utilizan las tablas de rendimiento de disco, se puede obtener la siguiente información:

* ¿Cuál es el rendimiento de un pool de almacenamiento específico en función de los datos de rendimiento de disco?
* ¿Cuál es el pool de almacenamiento más alto utilizado?
* ¿Cuál es el uso medio del disco para un almacenamiento específico?
* ¿Cuál es la tendencia de uso de un sistema de almacenamiento o un pool de almacenamiento en función de los datos de rendimiento de disco?
* ¿Cuál es la tendencia de uso de disco para un pool de almacenamiento específico?


Si utiliza las tablas de rendimiento de máquinas virtuales y VMDK, puede obtener la siguiente información:

* ¿Tiene el mejor rendimiento posible mi entorno virtual?
* ¿Qué VMDK notifican las cargas de trabajo más altas?
* ¿Cómo se puede utilizar el rendimiento informado en los equipos virtuales asignados a distintos almacenes de datos para tomar decisiones sobre la reorganización en niveles.


El modelo de datos de rendimiento incluye información que le ayuda a determinar la idoneidad de niveles, configuraciones erróneas de almacenamiento para aplicaciones y tiempos de último acceso de volúmenes y volúmenes internos. Este modelo de datos proporciona datos como tiempos de respuesta, IOPS, rendimiento, número de escrituras pendientes y estado de acceso.



=== Modelo de datos de eficiencia del almacenamiento

Le permite realizar un seguimiento de la puntuación en eficiencia del almacenamiento y de su potencial a lo largo del tiempo. Este modelo de datos almacena mediciones no solo de la capacidad aprovisionada, sino también de la cantidad usada o consumida (la medición física). Por ejemplo, cuando se habilita thin provisioning, Cloud Insights indica cuánta capacidad se toma del dispositivo. También puede usar este modelo para determinar la eficiencia cuando está activada la deduplicación. Puede responder a varias preguntas con el Data Mart de eficiencia del almacenamiento:

* ¿Cuáles son los ahorros que hemos conseguido en eficiencia del almacenamiento gracias a la implantación de tecnologías de thin provisioning y deduplicación?
* ¿Cuál es el ahorro de almacenamiento en los centros de datos?
* Según las tendencias de capacidad históricas, ¿cuándo necesitamos comprar almacenamiento adicional?
* ¿Qué aumento tendría la capacidad si habilitamos tecnologías como thin provisioning y deduplicación?
* En cuanto a la capacidad de almacenamiento, ¿estoy en riesgo ahora?




=== Tablas de hechos y dimensiones del modelo de datos

Cada modelo de datos incluye tablas de hechos y dimensiones.

* Tablas de hechos: Contienen datos que se miden, por ejemplo, cantidad, capacidad bruta y útil. Contiene claves externas para las tablas de dimensiones.
* Tablas de dimensiones: Contiene información descriptiva sobre hechos, por ejemplo, el centro de datos y las unidades de negocio. Una dimensión es una estructura, a menudo compuesta de jerarquías, que categoriza los datos. Los atributos dimensionales ayudan a describir los valores dimensionales.


Utilizando atributos de cota diferentes o múltiples (vistos como columnas en los informes), se construyen informes que tienen acceso a los datos de cada dimensión descrita en el modelo de datos.



=== Colores utilizados en los elementos del modelo de datos

Los colores de los elementos del modelo de datos tienen indicaciones diferentes.

* Activos amarillos: Representan mediciones.
* Activos no amarillos: Representan atributos. Estos valores no se agregan.




=== Uso de varios modelos de datos en un informe

Normalmente, se utiliza un modelo de datos por informe. Sin embargo, puede escribir un informe que combine datos de varios modelos de datos.

Para escribir un informe que combine datos de varios modelos de datos, elija uno de los modelos de datos que se van a utilizar como base y, a continuación, escriba consultas SQL para acceder a los datos de los marts de datos adicionales. Puede utilizar la función de unión de SQL para combinar los datos de las diferentes consultas en una única consulta que puede utilizar para escribir el informe.

Por ejemplo, supongamos que desea la capacidad actual para cada cabina de almacenamiento y desea capturar anotaciones personalizadas en las cabinas. Se puede crear el informe con el modelo de datos capacidad de almacenamiento. Puede utilizar los elementos de las tablas de capacidad y dimensiones actuales y agregar una consulta SQL independiente para tener acceso a la información de anotaciones en el modelo de datos de inventario. Finalmente, puede combinar los datos vinculando los datos de almacenamiento de inventario a la tabla Storage Dimension con el nombre del almacenamiento y los criterios de unión.
