---
sidebar: sidebar 
permalink: reporting_querying_database.html 
summary: Utilice las API de Cloud Insights para consultar directamente la base de datos de informes. 
keywords: reporting, cognos, data warehouse, dwh, API 
---
= Acceda a la base de datos de informes a través de API
:allow-uri-read: 


[role="lead"]
La potente API de Cloud Insights permite a los usuarios consultar directamente la base de datos de informes de Cloud Insights, sin pasar por el entorno de generación de informes de Cognos.


NOTE: Esta documentación hace referencia a la función Cloud Insights Reporting, que está disponible en link:/concept_subscribing_to_cloud_insights.html#editions["Edición Premium"].



== OData

La API de informes de Cloud Insights sigue la link:https://www.odata.org/["OData v4"] (Protocolo de datos abierto) estándar para su consulta de la base de datos de informes. Para obtener más información o para obtener más información, consulte link:https://www.odata.org/getting-started/basic-tutorial/["este tutorial"] En OData.

Todas las solicitudes se iniciarán con la URL _\https://<Cloud Insights URL>/Rest/v1/dwh-Management/odata_



== Generar una APIKey

Más información acerca de link:API_Overview.html["API de Cloud Insights"].

Para generar una clave de API, haga lo siguiente:

* Inicie sesión en su entorno Cloud Insights y seleccione *Admin > acceso API*.
* Haga clic en “+ API Access Token”.
* Introduzca un nombre y una descripción.
* Para el tipo, elija _Data Warehouse_.
* Establezca permisos como lectura/escritura.
* Defina una fecha de caducidad de deseos.
* Haga clic en “Guardar” y, a continuación, *copie la clave y guárdela* en un lugar seguro. No podrá acceder más tarde a la clave completa.


APIkeys es bueno para _Sync_ o _Async_.



== Consulta directa de tablas

Con la clave de API en vigor, ahora es posible realizar consultas directas de la base de datos de informes. Las direcciones URL largas se pueden simplificar a \https://.../odata/ con fines de visualización en lugar de \https://<Cloud Insights URL>/Rest/v1/dwh-Management/odata/

Pruebe consultas sencillas como

* \Https://<Cloud Insights URL>/Rest/v1/dwh-Management/odata/dwh_Custom
* \Https://<Cloud Insights URL>/Rest/v1/dwh-Management/odata/dwh_Inventory
* \Https://<Cloud Insights URL>/Rest/v1/dwh-Management/odata/dwh_Inventory/Storage
* \Https://<Cloud Insights URL>/Rest/v1/dwh-Management/odata/dwh_Inventory/Disk
* \https://.../odata/dwh_custom/custom_queries




== Ejemplos de API de REST

La URL para todas las llamadas es _\https://<Cloud Insights URL>/Rest/v1/dwh-Management/odata_.

* GET /{schema}/** - recupera datos de la base de datos de informes, requiere al menos la función _Guest_.


Formato: _\https://<Cloud Insights URL>/Rest/v1/dwh-Management/odata/<schema_name>/<query>_

Ejemplo:

 https://<domain>/rest/v1/dwh-management/odata/dwh_inventory/fabric?$count=true&$orderby=name
Resultado:

....
{
   "@odata.context": "$metadata#fabric",
   "@odata.count": 2,
   "value": [
       {
           "id": 851,
           "identifier": "10:00:50:EB:1A:40:3B:44",
           "wwn": "10:00:50:EB:1A:40:3B:44",
           "name": "10:00:50:EB:1A:40:3B:44",
           "vsanEnabled": "0",
           "vsanId": null,
           "zoningEnabled": "0",
           "url": "https://<domain>/web/#/assets/fabrics/941716"
       },
       {
           "id": 852,
           "identifier": "10:00:50:EB:1A:40:44:0C",
           "wwn": "10:00:50:EB:1A:40:44:0C",
           "name": "10:00:50:EB:1A:40:44:0C",
           "vsanEnabled": "0",
           "vsanId": null,
           "zoningEnabled": "0",
           "url": "https://<domain>/web/#/assets/fabrics/941836"
        }
    ]
}
....


== Sugerencias útiles

Tenga en cuenta lo siguiente al trabajar con consultas de la API de Reporting.

* La carga útil de consulta debe ser una cadena JSON válida
* La carga útil de la consulta debe estar contenida en una sola línea
* Se deben escapar las comillas dobles, es decir, \"
* Las fichas son compatibles como \t
* Evite comentarios
* Se admiten los nombres de tablas en minúsculas


Además:

* Se requieren 2 encabezados:
+
** Nombre “X-CloudInsights-ApiKey”
** Valor de atributo "<apikey>"




Su clave de API será específica para su entorno de Cloud Insights.
