---
sidebar: sidebar 
permalink: reporting_user_roles.html 
summary: Todo lo que puede hacer con los informes de Cloud Insights depende de la función de usuario. 
keywords: reporting, cognos, data warehouse, dwh, users, roles, user roles 
---
= Roles de usuario de informes de Cloud Insights
:allow-uri-read: 


[role="lead"]
Si tiene Cloud Insights Premium Edition con informes, cada usuario de Cloud Insights de su entorno también tiene un inicio de sesión único (SSO) en la aplicación de informes (es decir, Cognos). Simplemente haga clic en el enlace *Informes* del menú y se conectará automáticamente a Informes.

El rol de usuario en Cloud Insights determina el rol de usuario de generación de informes:

|===


| Cloud Insights | Función de creación de informes | Permisos de informes 


| Invitado | Consumidor | Puede ver, programar y ejecutar informes y establecer preferencias personales como las de idiomas y zonas horarias. Los consumidores no pueden crear informes ni realizar tareas administrativas. 


| Usuario | Autor | Puede realizar todas las funciones de usuario, así como crear y gestionar informes y paneles. 


| Administrador | Administrador | Puede realizar todas las funciones de Autor, así como todas las tareas administrativas como la configuración de informes y el cierre y reinicio de tareas de creación de informes. 
|===
En la siguiente tabla se muestran las funciones disponibles para cada rol de generación de informes.

|===


| Función | Consumidor | Autor | Administrador 


| Ver informes en la pestaña Contenido del equipo | Sí | Sí | Sí 


| Ejecutar informes | Sí | Sí | Sí 


| Programar informes | Sí | Sí | Sí 


| Cargue archivos externos | No | Sí | Sí 


| Crear trabajos | No | Sí | Sí 


| Crear historias | No | Sí | Sí 


| Crear informes | No | Sí | Sí 


| Crear paquetes y módulos de datos | No | Sí | Sí 


| Realizar tareas administrativas | No | No | Sí 
|===


== Configurar las preferencias de correo electrónico de generación de informes (Cognos)


NOTE: Si cambia sus preferencias de correo electrónico de usuario dentro de Cloud Insights Reporting (es decir, la aplicación Cognos), dichas preferencias estarán activas _sólo para la sesión_ actual. Cerrar sesión en Cognos y volver a ingresar restablecerá sus preferencias de correo electrónico.



== Nota importante para los clientes existentes

Si es nuevo en Cloud Insights con Informes, ¡Bienvenido! No hay nada más que usted necesita hacer para comenzar a disfrutar de Reporting.

Si ya es cliente de Premium Edition, SSO no se activa automáticamente para su entorno. Al habilitar SSO, el usuario administrador del portal de informes (Cognos) deja de existir. Esto significa que los informes que se encuentran en la carpeta _My Content_ se eliminan y deben volver a instalarse o crearse en _Team Content_. Además, los informes programados deberán configurarse una vez que se habilite el SSO.



=== ¿Qué pasos debo seguir para preparar mi entorno actual para habilitar SSO?

Para asegurarse de que sus informes se conservan, migre todos los informes de _My Content_ a _Team Content_ mediante los pasos siguientes. Debe hacerlo antes de habilitar SSO en su entorno:

. Cree una nueva carpeta en _Team Content_
+
.. Si se han creado varios usuarios, cree una carpeta independiente para que cada usuario evite sobrescribir informes con nombres duplicados


. Navegue hasta _My Content_
. Seleccione todos los informes que desee conservar.
. En la esquina superior derecha del menú, seleccione "Copiar o mover"
. Vaya a la carpeta recién creada en _Team Content_
. Pegue los informes en la carpeta recién creada mediante los botones "Copiar a" o "mover a"
. Una vez que SSO esté activado para Cognos, inicie sesión en Cloud Insights con la dirección de correo electrónico utilizada para crear su cuenta.
. Desplácese a la carpeta _Team Content_ dentro de Cognos y copie o mueva los informes guardados anteriormente a _My Content_.

