---
sidebar: sidebar 
permalink: task_dc_na_7mode.html 
keywords: data collector, 7-mode, NetApp 
summary: Configurar recopilador de datos de 7-Mode de NetApp. 
---
= Recopilador de datos de NetApp Data ONTAP con funcionamiento en 7-Mode
:allow-uri-read: 


[role="lead"]
En los sistemas de almacenamiento que utilizan el software Data ONTAP funcionando en 7-Mode, se utiliza el recopilador de datos de 7-Mode, que utiliza la CLI para obtener datos de capacidad y rendimiento.



== Terminología

Cloud Insights adquiere la siguiente información de inventario a través del recopilador de datos de 7-Mode de NetApp. Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Disco | Disco 


| Grupo RAID | Grupo de discos 


| Servidor dedicado a almacenamiento | Reducida 


| Servidor dedicado a almacenamiento | Nodo de almacenamiento 


| Agregado | Pool de almacenamiento 


| LUN | Volumen 


| Volumen | Volumen interno 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

Necesita lo siguiente para configurar y utilizar este recopilador de datos:

* Las direcciones IP de la controladora de almacenamiento de FAS y el asociado.
* Puerto 443
* Un nombre de usuario y contraseña de nivel de administrador personalizados para la controladora y la controladora asociada con las siguientes funcionalidades de rol para 7-Mode:
+
** "api-*": Utilice esto para permitir que OnCommand Insight ejecute todos los comandos de la API de almacenamiento de NetApp.
** "login-http-admin": Utilice esto para permitir que OnCommand Insight se conecte al almacenamiento de NetApp a través de HTTP.
** «Security-api-vfiler»: Utilice esto para permitir a OnCommand Insight ejecutar comandos de API de almacenamiento de NetApp para recuperar información de la unidad vFiler.
** "cli-options": Utilice esto para leer las opciones del sistema de almacenamiento.
** "cli-lun": Acceda a estos comandos para gestionar las LUN. Muestra el estado (ruta de LUN, tamaño, estado en línea/sin conexión y estado compartido) de la LUN o clase de LUN determinada.
** "cli-df": Utilice esta opción para mostrar el espacio libre en disco.
** "cli-ifconfig": Utilice esta opción para mostrar interfaces y direcciones IP.






== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección del sistema de almacenamiento | La dirección IP o el nombre de dominio completo para el sistema de almacenamiento de NetApp 


| Nombre de usuario | Nombre de usuario para el sistema de almacenamiento de NetApp 


| Contraseña | Contraseña para el sistema de almacenamiento de NetApp 


| Dirección del partner de alta disponibilidad en el clúster | La dirección IP o el nombre de dominio completo para el partner de alta disponibilidad 


| Nombre de usuario del partner de alta disponibilidad en el clúster | Nombre de usuario del partner de alta disponibilidad 


| Contraseña de almacenamiento para partners de alta disponibilidad en clúster | Contraseña para el partner de alta disponibilidad 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | Intervalo entre sondeos de inventario. El valor predeterminado es 20 minutos. 


| Tipo de conexión | HTTPS o HTTP, también muestra el puerto predeterminado 


| Anular puerto de conexión | Si está en blanco, utilice el puerto predeterminado en el campo Tipo de conexión; de lo contrario, introduzca el puerto de conexión que desea utilizar 


| Intervalo de sondeo de rendimiento (s) | Intervalo entre sondeos de rendimiento. El valor predeterminado es 300 segundos. 
|===


== Conexión de sistemas de almacenamiento

Como alternativa al uso del usuario administrativo predeterminado para este recopilador de datos, puede configurar un usuario con derechos administrativos directamente en los sistemas de almacenamiento de NetApp para que este recopilador de datos pueda adquirir datos de sistemas de almacenamiento de NetApp.

La conexión con los sistemas de almacenamiento NetApp requiere que el usuario, especificado al adquirir el pfilers principal (en el que existe el sistema de almacenamiento), cumpla las siguientes condiciones:

* El usuario debe estar en vfiler0 (archivador raíz/pfiler).
+
Los sistemas de almacenamiento se adquieren cuando se adquiere el filer principal.

* Los siguientes comandos definen las capacidades de los roles de usuario:
+
** "api-*": Utilice esto para permitir que Cloud Insights ejecute todos los comandos de la API de almacenamiento de NetApp.
+
Este comando es necesario para utilizar LA ZAPI.

** "login-http-admin": Utilice esto para permitir que Cloud Insights se conecte al almacenamiento de NetApp a través de HTTP. Este comando es necesario para utilizar LA ZAPI.
** «Security-api-vfiler»: Utilice esto para permitir a Cloud Insights ejecutar comandos de API de almacenamiento de NetApp para recuperar información de la unidad vFiler.
** "cli-options": Para el comando "OPTIONS" y se utiliza para la IP del partner y las licencias habilitadas.
** "cli-lun": Acceda a este comando para gestionar las LUN. Muestra el estado (ruta de LUN, tamaño, estado en línea/sin conexión y estado compartido) de la LUN o clase de LUN determinada.
** "cli-df": Para comandos "df -s", "df -r", "df -A -r" y se utiliza para mostrar espacio libre.
** "cli-ifconfig": Para el comando "ifconfig -a" y se utiliza para obtener la dirección IP del servidor de almacenamiento.
** "cli-rdfile": Para el comando "rdfile /etc/netgroup" y se utiliza para obtener grupos de red.
** "cli-date": Comando "date" y se usa para obtener la fecha completa para obtener las copias Snapshot.
** "cli-snap": Para el comando "snap list" y se utiliza para obtener copias snapshot.




Si no se proporcionan permisos date de cli o snap-cli, la adquisición puede finalizar, pero no se notifican las copias snapshot.

Para adquirir correctamente un origen de datos de 7-Mode y no generar ninguna advertencia en el sistema de almacenamiento, debe usar una de las siguientes cadenas de comandos para definir los roles de usuario. La segunda cadena que aparece aquí es una versión simplificada de la primera:

* login-http-admin,api-*,security-api-vfile,cli-rdfile,cli-options,cli-df,cli-lun,cli-ifconfig,cli-date,cli-snap,_
* login-http-admin,api-* ,security-api-vfile,cli-




== Resolución de problemas

Algunas cosas para intentar si tiene problemas con este recopilador de datos:



==== Inventario

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| Recibir respuesta HTTP 401 o código de error ZAPI 13003 y ZAPI devuelve “privilegios insuficientes” o “no autorizados para este comando” | Compruebe el nombre de usuario y la contraseña, así como los privilegios y permisos de usuario. 


| Error de “error al ejecutar el comando” | Compruebe si el usuario tiene el siguiente permiso en el dispositivo: • api-* • CLI-date • cli-df • cli-ifconfig • cli-lun • cli-opers • cli-rdfile • cli-snap • login-http-admin • Security-api-vfiler también comprueba si la versión de ONTAP es compatible con Cloud Insights y verifica si las credenciales utilizadas coinciden con las credenciales del dispositivo 


| La versión del clúster es < 8.1 | La versión mínima admitida del clúster es 8.1. Actualice a la versión mínima admitida. 


| ZAPI devuelve "el rol del clúster no es la LIF de gestión_clústeres" | AU necesita hablar con la IP de administración de clústeres. Compruebe la dirección IP y cambie a otra dirección IP si es necesario 


| Error: “Los servidores dedicados a almacenamiento de modo 7 no son compatibles” | Esto puede suceder si utiliza este recopilador de datos para descubrir el servidor dedicado a almacenamiento en modo 7. Cambie el IP para que apunte al archivador cdot. 


| El comando ZAPI falla después del reintento | AU tiene un problema de comunicación con el clúster. Compruebe la red, el número de puerto y la dirección IP. El usuario también debe intentar ejecutar un comando desde la línea de comandos desde la máquina AU. 


| AU no se ha conectado con ZAPI | Compruebe la conectividad IP/puerto y establezca la configuración DE ZAPI. 


| AU no pudo conectarse a ZAPI a través de HTTP | Compruebe si EL puerto ZAPI acepta texto sin formato. Si AU intenta enviar texto sin formato a un socket SSL, la comunicación falla. 


| La comunicación falla con SSLException | AU está intentando enviar SSL a un puerto de texto sin formato de un archivador. Compruebe si EL puerto ZAPI acepta SSL o utiliza un puerto diferente. 


| Errores de conexión adicionales: La respuesta ZAPI tiene el código de error 13001, “la base de datos no está abierta” el código DE error ZAPI es 60 y la respuesta contiene “la API no terminó a tiempo” la respuesta ZAPI contiene “initialize_Session() devolvió un entorno NULL” el código DE error ZAPI es 14007 y la respuesta contiene “el nodo no está en buen estado” | Compruebe la red, el número de puerto y la dirección IP. El usuario también debe intentar ejecutar un comando desde la línea de comandos desde la máquina AU. 


| Error de tiempo de espera del socket con ZAPI | Compruebe la conectividad de los servidores dedicados a almacenamiento o aumente el tiempo de espera. 


| Error “los clusters de modo C no son compatibles con el origen de datos de modo 7” | Compruebe la dirección IP y cambie la dirección IP a un clúster de 7 Mode. 


| Error de “no se ha podido conectar con vFiler” | Compruebe que la adquisición de las capacidades de usuario incluye lo siguiente como mínimo: api-* Security-api-vfiler login-http-admin confirma que el servidor de almacenamiento está ejecutando la versión mínima de ONAPI 1.7. 
|===
Puede encontrar información adicional en link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
