---
sidebar: sidebar 
permalink: task-moving-resource-groups-azure.html 
keywords: move resource groups, azure, remove working environment, resource groups, azure console, Azure subscriptions 
summary: Cloud Volumes ONTAP admite la transferencia de grupos de recursos de Azure, pero el flujo de trabajo solo ocurre en la consola de Azure. 
---
= Mover grupos de recursos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP admite la transferencia de grupos de recursos de Azure, pero el flujo de trabajo solo ocurre en la consola de Azure.

Puede mover un entorno de trabajo de un grupo de recursos a otro en Azure con la misma suscripción a Azure. No se admite el movimiento de grupos de recursos entre distintas suscripciones de Azure.

.Pasos
. Elimine el entorno de trabajo de *Canvas*.
+
Para aprender a eliminar un entorno de trabajo, consulte link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-removing.html["Eliminación de entornos de trabajo de Cloud Volumes ONTAP"].

. Ejecute el movimiento del grupo de recursos en la consola de Azure.
+
Para completar el movimiento, consulte link:https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription["Mueva los recursos a un nuevo grupo de recursos o suscripción en la documentación de Microsoft Azure"^].

. En *Canvas*, descubre el entorno de trabajo.
. Busque el nuevo grupo de recursos en la información del entorno de trabajo.


.Resultado
El entorno de trabajo y sus recursos (VM, discos, cuentas de almacenamiento, interfaces de red, snapshots) se encuentran en el nuevo grupo de recursos.
