---
sidebar: sidebar 
permalink: task_dc_openstack.html 
keywords: data collector, openstack, OpenStack 
summary: Recopilador de datos de OpenStack. 
---
= Recopilador de datos de OpenStack
:allow-uri-read: 


[role="lead"]
El recopilador de datos de OpenStack (API DE REST/KVM) adquiere datos de inventario para todas las instancias de OpenStack y, opcionalmente, los datos de rendimiento de las máquinas virtuales.



== Requisitos

* La dirección IP de la controladora OpenStack
* Credencial de rol de administrador de OpenStack y acceso sudo al hipervisor KVM de Linux. Si no está utilizando la cuenta de administrador o privilegios equivalentes del administrador, necesitará usar la prueba y el error para identificar las directivas predeterminadas para relajarse para el ID de usuario del recopilador de datos.
* El módulo OpenStack Ceilometer debe instalarse y configurarse para la recogida de rendimiento. La configuración del Ceilometer se realiza editando el archivo nova.conf para cada hipervisor y, a continuación, reiniciando el servicio de computación Nova en cada hipervisor. La opción cambia de nombre para diferentes versiones de OpenStack:
+
** Icehouse
** Juno
** Kilo
** Libertad
** Mitaka
** Newton
** Ocata


* Para las estadísticas de CPU, “Compute_Monitores=ComputeDriverCPUMonitor” debe estar activado en /etc/nova/nova.conf en nodos de computación.
* Requisitos de puerto:
+
** 5000 para http y 13000 para https, para el servicio Keystone
** 22 para SSH KVM
** 8774 para Nova Compute Service
** 8776 para Cinder Block Service
** 8777 para el servicio de rendimiento Ceilometer
** 9292 para el servicio Glance Image Service *Nota* el puerto se enlaza al servicio específico y el servicio puede ejecutarse en el controlador u otro host en entornos más grandes.






== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP de la controladora OpenStack | La dirección IP o el nombre de dominio completo del controlador OpenStack 


| Administrador de OpenStack | Nombre de usuario para un administrador de OpenStack 


| Contraseña de OpenStack | La contraseña que se usa para el administrador de OpenStack 


| Inquilino de administrador de OpenStack | Nombre de inquilino del administrador de OpenStack 


| Usuario sudo KVM | Nombre de usuario sudo KVM 


| Elija 'Contraseña' o 'Archivo de claves OpenSSH' para especificar el tipo de credencial | Tipo de credencial utilizado para conectarse al dispositivo a través de SSH 


| Ruta completa a la clave privada de inventario | Ruta completa a la clave privada de inventario 


| Contraseña sudo KVM | Contraseña sudo KVM 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Habilite la detección de inventario del hipervisor a través de SSH | Compruebe esto para habilitar la detección de inventario de hipervisor a través de SSH 


| Puerto de URL de administrador de OpenStack | Puerto de URL de administrador de OpenStack 


| Utilice HTTPS | Compruebe que utilice HTTP seguro 


| Puerto SSH | Puerto utilizado para SSH 


| Reintentos de proceso SSH | Número de intentos de reintento de inventario 


| Intervalo de sondeo de inventario (mín.) | Intervalo entre sondeos de inventario. El valor predeterminado es 20 minutos. 
|===


== Resolución de problemas

Algunas cosas para intentar si tiene problemas con este recopilador de datos:



==== Inventario

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| "Error de configuración" con mensajes de error empiezan por "la directiva no permite" o "no está autorizado" | * Compruebe la dirección ip * Compruebe el nombre de usuario y la contraseña 
|===
Puede encontrar información adicional en link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
