---
sidebar: sidebar 
permalink: task_create_annotation.html 
keywords: annotations, annotation rules, manual annotations, 
summary: Cómo crear una anotación. 
---
= Uso de anotaciones
:allow-uri-read: 


[role="lead"]
Cree anotaciones y asígnelas a los activos que supervisa. Las anotaciones son notas que proporcionan información sobre un activo, como la ubicación física, el fin de vida, el nivel de almacenamiento o los niveles de servicio de volumen.



== Definición de anotaciones

Con las anotaciones, puede agregar datos personalizados específicos del negocio que se ajusten a los activos de las necesidades del negocio. Aunque Cloud Insights proporciona un conjunto de anotaciones predeterminadas, como el ciclo de vida de activos (cumpleaños o fin de su vida), la ubicación del centro de datos o edificio y el nivel, es posible que desee ver los datos de otras formas.

Los datos de anotaciones personalizadas complementan los datos del dispositivo ya recopilados, como el fabricante del switch, el número de puertos y las estadísticas de rendimiento. Cloud Insights no detecta los datos que se agregan con anotaciones.

.Antes de empezar
* Enumere cualquier terminología del sector a la que deben asociarse los datos del entorno.
* Enumerar la terminología corporativa a la que deben asociarse los datos del entorno.
* Identifique los tipos de anotaciones predeterminados que pueda utilizar.
* Identifique qué anotaciones personalizadas debe crear. Debe crear la anotación para poder asignarla a un activo.


Utilice los siguientes pasos para crear una anotación.

.Pasos
. En el menú Cloud Insights, haga clic en *Administrar > Anotaciones*
. Haga clic en *+ anotación* para crear una nueva anotación.
. Introduzca un nombre, una descripción y un tipo para la nueva anotación.
+
Por ejemplo, escriba lo siguiente para crear una anotación de texto que defina la ubicación física de un activo en el Centro de datos 4:

+
** Escriba un nombre para la anotación, como "ubicación".
** Introduzca una descripción de lo que describe la anotación, como "la ubicación física es el centro de datos 4".
** Introduzca el "tipo" de anotación que es, como "texto".






== Asignación manual de anotaciones a activos

La asignación de anotaciones a activos ayuda a ordenar, agrupar e informar sobre los activos de forma que sean relevantes para su negocio. Aunque puede asignar anotaciones a activos de un tipo concreto automáticamente mediante reglas de anotación, puede asignar anotaciones a un activo individual mediante su página de activos.

.Antes de empezar
* Debe haber creado la anotación que desea asignar.


.Pasos
. Inicie sesión en su entorno de Cloud Insights.
. Busque el activo al que desea aplicar la anotación.
+
** Puede buscar activos consultando, eligiendo de un widget de dashoard o buscando. Cuando haya localizado el activo que desee, haga clic en el enlace para abrir la página de destino del activo.


. En la página Asset, en la sección User Data, haga clic en *+ Annotation*.
. Aparece el cuadro de diálogo Agregar anotación.
. Seleccione una anotación de la lista.
. Haga clic en valor y realice una de las siguientes acciones, según el tipo de anotación que haya seleccionado:
+
** Si el tipo de anotación es lista, fecha o booleano, seleccione un valor de la lista.
** Si el tipo de anotación es texto, escriba un valor.


. Haga clic en *Guardar*.


Si desea cambiar el valor de la anotación después de asignarla, haga clic en el campo de anotación y seleccione un valor diferente. Si la anotación es del tipo de lista para el que está seleccionada la opción _Add new Values on the Fly_, puede escribir un nuevo valor además de seleccionar un valor existente.



== Asignación de anotaciones mediante reglas de anotación

Para asignar anotaciones automáticamente a activos basándose en los criterios definidos, configure reglas de anotación. Cloud Insights asigna las anotaciones a los activos basándose en estas reglas. Cloud Insights también proporciona dos reglas de anotación predeterminadas, que se pueden modificar para ajustarse a sus necesidades o quitar si no desea utilizarlas.



=== Creación de reglas de anotación

Como alternativa a la aplicación manual de anotaciones a activos individuales, puede aplicar anotaciones automáticamente a varios activos mediante reglas de anotación. Las anotaciones definidas manualmente en una página de activos individual tienen prioridad sobre las anotaciones basadas en reglas cuando Insight evalúa las reglas de anotación.

.Antes de empezar
Debe haber creado una consulta para la regla de anotación.

.Acerca de esta tarea
Aunque puede editar los tipos de anotaciones mientras crea las reglas, debe haber definido los tipos con anticipación.

.Pasos
. Haga clic en *Administrar > Reglas de anotación*
+
La página Reglas de anotación muestra la lista de reglas de anotación existentes.

. Haga clic en *+ Agregar*.
. Haga lo siguiente:
+
.. En el cuadro *Nombre*, escriba un nombre único que describa la regla.
+
Este nombre aparecerá en la página Reglas de anotación.

.. Haga clic en *Consulta* y seleccione la consulta que se utiliza para aplicar la anotación a los activos.
.. Haga clic en *anotación* y seleccione la anotación que desea aplicar.
.. Haga clic en *valor* y seleccione un valor para la anotación.
+
Por ejemplo, si selecciona Cumpleaños como anotación, especifique una fecha para el valor.

.. Haga clic en *Guardar*
.. Haga clic en *Ejecutar todas las reglas* si desea ejecutar todas las reglas inmediatamente; de lo contrario, las reglas se ejecutarán a un intervalo programado regularmente.



