---
sidebar: sidebar 
permalink: task_dc_emc_scaleio.html 
keywords: data collector, scaleIO, EMC, DELL 
summary: Configurar el recopilador DE datos Dell EMC ScaleIO. 
---
= Recopilador DE datos Dell EMC ScaleIO
:allow-uri-read: 


[role="lead"]
El recopilador de datos de ScaleIO recopila información de inventario del almacenamiento de ScaleIO. Para la configuración, este recopilador de datos requiere la dirección de puerta de enlace ScaleIO y el nombre de usuario y la contraseña de administrador.



== Terminología

Cloud Insights adquiere la siguiente información de inventario del recopilador de datos de ScaleIO. Para cada tipo de activo adquirido por Cloud Insights, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Clúster MDM (Meta Data Manager) | Reducida 


| SDS (servidor de datos ScaleIO) | Nodo de almacenamiento 


| Pool de almacenamiento | Pool de almacenamiento 


| Volumen | Volumen 


| Dispositivo | Disco 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* Acceso de solo lectura a la cuenta de usuario administrador
* Requisito de puerto: Puerto HTTPS 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Puertas de enlace ScaleIO | Direcciones IP o FQDN de puertas de enlace ScaleIO separadas por comas (,) o punto y coma (;) 


| Nombre de usuario | Nombre de usuario de administrador utilizado para iniciar sesión en el dispositivo ScaleIO 


| Contraseña | Contraseña utilizada para iniciar sesión en el dispositivo ScaleIO 
|===


== Configuración avanzada

Haga clic en la casilla de verificación Inventario para habilitar la recopilación de inventario.

[cols="2*"]
|===
| Campo | Descripción 


| Puerto HTTPS | 443 


| Intervalo de sondeo de inventario (min) | El valor predeterminado es 60. 


| Tiempo de espera de conexión (s) | El valor predeterminado es 60. 
|===


== Resolución de problemas

Puede encontrar información adicional en link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
