---
sidebar: sidebar 
permalink: task-planning-your-config-gcp.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported machine types, supported virtual machines, supported vms, supported instances 
summary: Al poner en marcha Cloud Volumes ONTAP, puede elegir un sistema preconfigurado que se ajuste a los requisitos de la carga de trabajo, o bien puede crear su propia configuración. Si elige su propia configuración, debe conocer las opciones disponibles. 
---
= Planifique la configuración de Cloud Volumes ONTAP en Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Al poner en marcha Cloud Volumes ONTAP en Google Cloud, puede elegir un sistema preconfigurado que se ajuste a los requisitos de la carga de trabajo, o puede crear su propia configuración. Si elige su propia configuración, debe conocer las opciones disponibles.



== Seleccione una licencia de Cloud Volumes ONTAP

Hay varias opciones de licencia disponibles para Cloud Volumes ONTAP. Cada opción le permite elegir un modelo de consumo que cumpla sus necesidades.

* link:concept-licensing.html["Obtenga información sobre las opciones de licencia para Cloud Volumes ONTAP"]
* link:task-set-up-licensing-google.html["Aprenda a configurar las licencias"]




== Seleccione una región admitida

Cloud Volumes ONTAP es compatible en la mayoría de las regiones de Google Cloud. https://cloud.netapp.com/cloud-volumes-global-regions["Consulte la lista completa de las regiones admitidas"^].



== Seleccione un tipo de máquina admitido

Cloud Volumes ONTAP admite varios tipos de máquinas, según el tipo de licencia que elija.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Configuraciones admitidas para Cloud Volumes ONTAP en GCP"^]



== Comprender los límites de almacenamiento

El límite de capacidad bruta de un sistema de Cloud Volumes ONTAP está relacionado con la licencia. Los límites adicionales afectan al tamaño de los agregados y los volúmenes. Debe conocer estos límites a medida que planifique la configuración.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-gcp.html["Límites de almacenamiento para Cloud Volumes ONTAP en GCP"^]



== Ajuste el tamaño de su sistema en GCP

Configurar el tamaño de su sistema Cloud Volumes ONTAP puede ayudarle a cumplir los requisitos de rendimiento y capacidad. Al elegir un tipo de máquina, un tipo de disco y un tamaño de disco, es necesario tener en cuenta algunos puntos clave:

Tipo de máquina:: Observe los tipos de máquina admitidos en la http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["Notas de la versión de Cloud Volumes ONTAP"^] Y luego revise los detalles de Google sobre cada tipo de máquina compatible. Haga coincidir los requisitos de carga de trabajo con el número de vCPU y memoria para el tipo de máquina. Tenga en cuenta que cada núcleo de CPU aumenta el rendimiento de la red.
+
--
Consulte lo siguiente para obtener más información:

* https://cloud.google.com/compute/docs/machine-types#n1_machine_types["Documentación de Google Cloud: Tipos de máquina estándar N1"^]
* https://cloud.google.com/docs/compare/data-centers/networking#performance["Documentación de Google Cloud: Rendimiento"^]


--
Tipo de disco para GCP:: Cuando crea volúmenes para Cloud Volumes ONTAP, debe elegir el almacenamiento en cloud subyacente que utiliza Cloud Volumes ONTAP para un disco. El tipo de disco puede ser cualquiera de los siguientes:
+
--
* _Zonal SSD persistent disks_: Los discos persistentes de SSD son la mejor opción para cargas de trabajo que requieren altas tasas de IOPS aleatorias.
* _Zonal discos persistentes equilibrados_: Estos SSD equilibran el rendimiento y el coste al proporcionar un menor número de IOPS por GB.
* _Zonal Standard persistent disks_ : los discos persistentes estándar son económicos y pueden manejar operaciones secuenciales de lectura y escritura.
+
Para obtener información detallada, consulte https://cloud.google.com/compute/docs/disks/#pdspecs["Documentación de Google Cloud: Discos persistentes zonal (Standard y SSD)"^].



--
Tamaño de discos para GCP:: Debe seleccionar un tamaño de disco inicial al poner en marcha un sistema Cloud Volumes ONTAP. Después puede dejar que BlueXP gestione la capacidad de un sistema por usted, pero si desea crear agregados por su cuenta, tenga en cuenta lo siguiente:
+
--
* Todos los discos de un agregado deben tener el mismo tamaño.
* Determine el espacio que necesita, teniendo en cuenta el rendimiento.
* El rendimiento de los discos persistentes se amplía automáticamente con el tamaño del disco y el número de vCPU disponibles para el sistema.
+
Consulte lo siguiente para obtener más información:

+
** https://cloud.google.com/compute/docs/disks/#pdspecs["Documentación de Google Cloud: Discos persistentes zonal (Standard y SSD)"^]
** https://cloud.google.com/compute/docs/disks/performance["Documentación de Google Cloud: Optimización del rendimiento de discos persistentes y SSD locales"^]




--




== Ver los discos del sistema predeterminados

Además del almacenamiento de los datos de usuario, BlueXP también adquiere almacenamiento en cloud para los datos del sistema Cloud Volumes ONTAP (datos de arranque, datos raíz, datos principales y NVRAM). Para fines de planificación, es posible que le ayude a revisar estos detalles antes de implementar Cloud Volumes ONTAP.

* link:reference-default-configs.html#google-cloud-single-node["Vea los discos predeterminados para los datos del sistema Cloud Volumes ONTAP en Google Cloud"].
* https://cloud.google.com/compute/quotas["Documentos de Google Cloud: Cuotas de recursos"^]
+
Google Cloud Compute Engine aplica cuotas al uso de recursos, por lo que debe asegurarse de que no ha alcanzado su límite antes de implementar Cloud Volumes ONTAP.




TIP: El conector también requiere un disco del sistema. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["Ver detalles sobre la configuración predeterminada del conector"^].



== Recopilar información de red

Al implementar Cloud Volumes ONTAP en GCP, debe especificar los detalles de su red virtual. Puede utilizar una hoja de cálculo para recopilar la información del administrador.

*Información de red para un sistema de un solo nodo*

[cols="30,70"]
|===
| Información para GCP | Su valor 


| Región |  


| Zona |  


| Red VPC |  


| Subred |  


| Política de firewall (si utiliza la suya propia) |  
|===
*Información de red para un par ha en varias zonas*

[cols="30,70"]
|===
| Información para GCP | Su valor 


| Región |  


| Zona para el nodo 1 |  


| Zona para nodo 2 |  


| Zona para el mediador |  


| VPC-0 y subred |  


| VPC-1 y subred |  


| VPC-2 y subred |  


| VPC-3 y subred |  


| Política de firewall (si utiliza la suya propia) |  
|===
*Información de red para un par ha en una sola zona*

[cols="30,70"]
|===
| Información para GCP | Su valor 


| Región |  


| Zona |  


| VPC-0 y subred |  


| VPC-1 y subred |  


| VPC-2 y subred |  


| VPC-3 y subred |  


| Política de firewall (si utiliza la suya propia) |  
|===


== Elija una velocidad de escritura

BlueXP le permite elegir una configuración de velocidad de escritura para Cloud Volumes ONTAP, excepto los pares de alta disponibilidad (ha) en Google Cloud. Antes de elegir una velocidad de escritura, debe comprender las diferencias entre la configuración normal y la alta, así como los riesgos y recomendaciones cuando utilice la alta velocidad de escritura. link:concept-write-speed.html["Más información sobre la velocidad de escritura"].



== Seleccione un perfil de uso de volumen

ONTAP incluye varias funciones de eficiencia del almacenamiento que pueden reducir la cantidad total de almacenamiento que necesita. Al crear un volumen en BlueXP, puede elegir un perfil que habilite estas funciones o un perfil que las desactive. Debe obtener más información sobre estas funciones para ayudarle a decidir qué perfil utilizar.

Las funciones de eficiencia del almacenamiento de NetApp ofrecen las siguientes ventajas:

Aprovisionamiento ligero:: Presenta más almacenamiento lógico a hosts o usuarios del que realmente hay en el pool de almacenamiento físico. En lugar de asignar previamente espacio de almacenamiento, el espacio de almacenamiento se asigna de forma dinámica a cada volumen a medida que se escriben los datos.
Deduplicación:: Mejora la eficiencia al localizar bloques de datos idénticos y sustituirlos con referencias a un único bloque compartido. Esta técnica reduce los requisitos de capacidad de almacenamiento al eliminar los bloques de datos redundantes que se encuentran en un mismo volumen.
Compresión:: Reduce la capacidad física requerida para almacenar datos al comprimir los datos de un volumen en almacenamiento primario, secundario y de archivado.

