---
sidebar: sidebar 
permalink: task_dc_ibm_powervm.html 
keywords: IBM, powerVM, 
summary: Configurar el recopilador de datos de IBM PowerVM. 
---
= Configurar el recopilador de datos de IBM PowerVM
:allow-uri-read: 


[role="lead"]
El recopilador de datos de IBM PowerVM (SSH) se utiliza para recopilar información acerca de las particiones virtuales que se ejecutan en instancias de hardware DE IBM POWER gestionadas por una consola de administración de hardware (HMC).



== Terminología

Cloud Insights adquiere información de inventario de las particiones virtuales que se ejecutan en instancias de hardware IBM POWER. Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para el activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| disco hdisk | Disco virtual 


| Sistema gestionado | Host 


| LPAR, servidor VIO | Máquina virtual 


| Grupo de volúmenes | Almacén de datos 


| Volumen físico | LUN 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

Se deben cumplir los siguientes requisitos para configurar y utilizar este recopilador de datos:

* Dirección IP de la Consola de administración de hardware (HMC)
* Nombre de usuario y contraseña que proporcionan acceso a hardware Management Console (HMC) a través de SSH
* Se requiere el puerto SSH-22
* Permiso de vista en todos los sistemas de administración y dominios de seguridad de partición lógica
+
El usuario también debe tener permiso View en las configuraciones HMC y la capacidad de recopilar información de VPD para la agrupación de seguridad de la consola HMC. También se debe permitir al usuario el acceso al comando de servidor de E/S virtual en la agrupación de seguridad de partición lógica. Es una práctica recomendada empezar desde un rol de operador y después quitar todas las funciones. Los usuarios de sólo lectura de HMC no tienen privilegios para ejecutar comandos proxy en hosts AIX.

* La mejor práctica de IBM es tener los dispositivos controlados por dos o más HMC. Tenga en cuenta que esto puede provocar que OnCommand Insight informe de dispositivos duplicados, por lo que se recomienda encarecidamente agregar dispositivos redundantes a la lista "excluir dispositivos" de la configuración avanzada de este recopilador de datos.




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP de la consola de administración de hardware (HMC) | Dirección IP o nombre de dominio completo de PowerVM hardware Management Console 


| Usuario de HMC | Nombre de usuario de la Consola de administración de hardware 


| Contraseña | Contraseña utilizada para la Consola de administración de hardware 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | Intervalo entre sondeos de inventario. El valor predeterminado es 20 minutos. 


| Puerto SSH | Puerto que se utiliza para SSH al PowerVM 


| Contraseña | Contraseña utilizada para la Consola de administración de hardware 


| Número de reintentos | Número de intentos de reintento de inventario 


| Excluir dispositivos | Lista separada por comas de ID de dispositivo o nombres de visualización que se van a excluir 
|===


== Resolución de problemas

Se puede encontrar información adicional sobre este colector de datos en la link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
