---
sidebar: sidebar 
permalink: task_dc_emc_powerstore.html 
keywords: data collector, PowerStore, EMC, DELL 
summary: Configuración del recopilador DE datos Dell EMC PowerStore. 
---
= Recopilador de datos de Dell EMC PowerStore
:allow-uri-read: 


[role="lead"]
El recopilador de datos de EMC PowerStore recopila información de inventario del almacenamiento de EMC PowerStore. Para la configuración, el recopilador de datos requiere la dirección IP de los procesadores de almacenamiento y un nombre de usuario y contraseña de sólo lectura.

El recopilador de datos de EMC PowerStore recopila las relaciones de replicación de volumen a volumen que PowerStore coordina en otras cabinas de almacenamiento. Cloud Insights muestra una cabina de almacenamiento para cada clúster de PowerStore, y recopila datos de inventario para los nodos y los puertos de almacenamiento de ese clúster. No se recopilan datos de volúmenes o pool de almacenamiento.



== Terminología

Cloud Insights adquiere la siguiente información de inventario de este recopilador de datos. Para cada tipo de activo adquirido por Cloud Insights, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| host | host 


| asignación_volumen_host | asignación_volumen_host 


| Hardware (tiene unidades bajo objeto "extra_details"): Unidades | Disco 


| Dispositivo | StoragePool 


| Clúster | Cabina de almacenamiento 


| Nodo | Nodo de almacenamiento 


| puerto_fc | Puerto 


| volumen | Volumen 


| InternalVolume | sistema_de_archivos 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

Para configurar este recopilador de datos se necesita la siguiente información:

* Dirección IP o nombre de dominio completo del procesador de almacenamiento
* Nombre de usuario y contraseña de solo lectura




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Puertas de enlace PowerStore | Direcciones IP o nombres de dominio completos de almacenamiento PowerStore 


| Nombre de usuario | Nombre de usuario de PowerStore 


| Contraseña | Contraseña usada para PowerStore 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto HTTPS | El valor predeterminado es 443 


| Intervalo de sondeo de inventario (minutos) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 
|===
La colección de rendimiento PowerStore de Cloud Insight utiliza los datos de fuente de granularidad de 5 minutos de PowerStore. De este modo, Cloud Insights sondea esos datos cada cinco minutos; por el contrario, no se puede configurar.



== Resolución de problemas

Se puede encontrar información adicional sobre este colector de datos en la link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
