---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: Configurar recopilador de datos de StorageGRID de NetApp 
keywords: data collector, queries, create, storagegrid 
---
= Recopilador de datos de NetApp StorageGRID
:allow-uri-read: 


[role="lead"]
El recopilador de datos de StorageGRID de NetApp admite el inventario y la recopilación de rendimiento de las configuraciones de StorageGRID.


NOTE: La medición de StorageGRID se realiza a una tasa de TB bruta diferente a la de la unidad gestionada. Cada 40 TB de capacidad StorageGRID sin formato se carga como 1 link:concept_subscribing_to_cloud_insights.html#pricing["Unidad administrada (UM)"].



== Requisitos

A continuación se muestran los requisitos para configurar este origen de datos:

* Dirección IP del host StorageGRID
* Nombre de usuario y contraseña para un usuario que tiene asignadas las funciones de consulta métrica y acceso de inquilino
* Puerto 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP del host StorageGRID | La dirección IP virtual de gestión del dispositivo StorageGRID 


| Nombre de usuario | Nombre que se utiliza para iniciar sesión en el dispositivo StorageGRID 


| Contraseña | Contraseña utilizada para iniciar sesión en el dispositivo StorageGRID 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | El valor predeterminado es 60 minutos 


| Intervalo de sondeo de rendimiento (s) | El valor predeterminado es 900 segundos 
|===


== Resolución de problemas

Se puede encontrar información adicional sobre este colector de datos en la link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
