---
sidebar: sidebar 
permalink: task_create_application.html 
summary: Se crean reglas de anotación para aplicar anotaciones automáticamente a varios activos basándose en los criterios definidos. 
keywords: application, create application, 
---
= Creación de aplicaciones
:allow-uri-read: 


[role="lead"]
Para realizar un seguimiento de los datos asociados con aplicaciones específicas que se ejecutan en su entorno, puede definir las aplicaciones en Cloud Insights.

.Antes de empezar
Si desea asociar la aplicación a una entidad de negocio, debe crear la entidad de negocio antes de definir la aplicación.

.Acerca de esta tarea
Cloud Insights le permite realizar un seguimiento de los datos de los activos asociados con las aplicaciones en relación con aspectos como el uso o la creación de informes de costes.

.Pasos
. En el menú Cloud Insights, haga clic en *Administrar > aplicaciones*.

+ aparece el cuadro de diálogo Agregar aplicación.

. Introduzca un nombre único para la aplicación.
. Seleccione una prioridad para la aplicación.
. Haga clic en *Guardar*.


.Después de terminar
Después de definir una aplicación, se puede asignar a activos.



== Asignar aplicaciones a activos

Este procedimiento asigna la aplicación a un host como ejemplo. Es posible asignar volúmenes host, de máquina virtual, de volumen o internos a una aplicación.

.Pasos
. Busque el activo al que desea asignar a la aplicación:
. Haga clic en *consultas > +Nueva consulta* y busque Host.
. Haga clic en la casilla de verificación situada a la izquierda del host que desea asociar a la aplicación.
. Haga clic en *acciones masivas > Agregar aplicación*.
. Seleccione la aplicación a la que está asignando el activo.


.Después de terminar
Después de asignar el host a la aplicación, puede asignar los activos restantes a la aplicación. Para acceder a la página de inicio de la aplicación, haga clic en *Administrar > aplicación* y seleccione la aplicación que creó.
