---
sidebar: sidebar 
permalink: task-verify-autosupport.html 
keywords: autosupport, set up autosupport, test autosupport, asup, test asup 
summary: AutoSupport supervisa de manera proactiva el estado del sistema y envía mensajes al soporte técnico de NetApp. De manera predeterminada, AutoSupport se habilita en cada nodo para enviar mensajes al soporte técnico mediante el protocolo de transporte HTTPS. Es mejor comprobar que AutoSupport puede enviar estos mensajes. 
---
= Comprobar la configuración de AutoSupport
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AutoSupport supervisa de manera proactiva el estado del sistema y envía mensajes al soporte técnico de NetApp. De manera predeterminada, AutoSupport se habilita en cada nodo para enviar mensajes al soporte técnico mediante el protocolo de transporte HTTPS. Es mejor comprobar que AutoSupport puede enviar estos mensajes.

El único paso de configuración requerido es asegurarse de que Cloud Volumes ONTAP tiene conectividad de salida a Internet. Para obtener más información, consulte los requisitos de red de su proveedor de cloud.



== Requisitos de AutoSupport

Los nodos Cloud Volumes ONTAP requieren acceso a Internet de salida para AutoSupport de NetApp, que supervisa de forma proactiva el estado del sistema y envía mensajes al soporte técnico de NetApp.

Las políticas de enrutamiento y firewall deben permitir el tráfico HTTP/HTTPS a los siguientes extremos para que Cloud Volumes ONTAP pueda enviar mensajes de AutoSupport:

* \https://support.netapp.com/aods/asupmessage
* \https://support.netapp.com/asupprod/post/1.0/postAsup


Si una conexión a Internet saliente no está disponible para enviar mensajes AutoSupport, BlueXP configura automáticamente sus sistemas Cloud Volumes ONTAP para utilizar el conector como servidor proxy. El único requisito es asegurarse de que el grupo de seguridad del conector permita conexiones _entrante_ a través del puerto 3128. Tendrá que abrir este puerto después de desplegar el conector.

Si ha definido reglas de salida estrictas para Cloud Volumes ONTAP, también tendrá que asegurarse de que el grupo de seguridad Cloud Volumes ONTAP permita conexiones _saliente_ a través del puerto 3128.

Una vez que haya comprobado que el acceso saliente a Internet está disponible, puede probar AutoSupport para asegurarse de que puede enviar mensajes. Para obtener instrucciones, consulte https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html["Documentos de ONTAP: Configure AutoSupport"^].



== Solucione problemas de configuración de AutoSupport

Si no hay una conexión de salida disponible y BlueXP no puede configurar el sistema Cloud Volumes ONTAP para que utilice el conector como servidor proxy, recibirá una notificación de BlueXP titulada "<working environment name> no puede enviar mensajes de AutoSupport".

Lo más probable es que reciba este mensaje debido a problemas de red.

Siga estos pasos para solucionar este problema.

.Pasos
. SSH al sistema Cloud Volumes ONTAP para poder administrar el sistema desde la CLI.
+
link:task-connecting-to-otc.html["Descubra cómo de SSH a Cloud Volumes ONTAP"].

. Muestre el estado detallado del subsistema AutoSupport:
+
`autosupport check show-details`

+
La respuesta debe ser similar a la siguiente:

+
[listing]
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
Si el estado de la categoría http-https es "ok", significa que AutoSupport está configurado correctamente y que pueden enviarse mensajes.

. Si el estado no es correcto, compruebe la URL del proxy de cada nodo Cloud Volumes ONTAP:
+
`autosupport show -fields proxy-url`

. Si el parámetro URL del proxy está vacío, configure Cloud Volumes ONTAP para que utilice el conector como proxy:
+
`autosupport modify -proxy-url \http://<connector private ip>:3128`

. Vuelva a verificar el estado de AutoSupport:
+
`autosupport check show-details`

. Si el estado es aún con errores, compruebe que haya conectividad entre Cloud Volumes ONTAP y el conector sobre el puerto 3128.
. Si el identificador de estado sigue fallando después de verificar que hay conectividad, SSH al conector.
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-connectors.html#connect-to-the-linux-vm["Más información sobre cómo conectarse a la VM de Linux para el conector"^]

. Vaya a. `/opt/application/netapp/cloudmanager/docker_occm/data/`
. Abra el archivo de configuración del proxy `squid.conf`
+
La estructura básica del archivo es la siguiente:

+
[listing]
----
        http_port 3128
        acl localnet src 172.31.0.0/16
        acl azure_aws_metadata dst 169.254.169.254

        http_access allow localnet
        http_access deny azure_aws_metadata
        http_access allow localhost
        http_access deny all
----
+
El valor localnet src es el CIDR del sistema Cloud Volumes ONTAP.

. Si el bloque CIDR del sistema Cloud Volumes ONTAP no está en el rango especificado en el archivo, actualice el valor o añada una nueva entrada de la siguiente manera:
+
`acl cvonet src <cidr>`

+
Si añade esta nueva entrada, no olvide agregar también una entrada permitir:

+
`http_access allow cvonet`

+
Veamos un ejemplo:

+
[listing]
----
        http_port 3128
        acl localnet src 172.31.0.0/16
        acl cvonet src 172.33.0.0/16
        acl azure_aws_metadata dst 169.254.169.254

        http_access allow localnet
        http_access allow cvonet
        http_access deny azure_aws_metadata
        http_access allow localhost
        http_access deny all
----
. Después de editar el archivo de configuración, reinicie el contenedor proxy como sudo:
+
`docker restart squid`

. Vuelva a la CLI de Cloud Volumes ONTAP y compruebe que Cloud Volumes ONTAP puede enviar mensajes de AutoSupport:
+
`autosupport check show-details`


