---
sidebar: sidebar 
permalink: task_dc_na_cdot.html 
keywords: data collector, ontap, ontap, CDOT 
summary: Recopilador de datos de ONTAP 
---
= Recopilador de datos del software de gestión de datos ONTAP de NetApp
:allow-uri-read: 


[role="lead"]
Este recopilador de datos adquiere datos de inventario y rendimiento de sistemas de almacenamiento que ejecutan ONTAP mediante llamadas API de solo lectura de una cuenta de ONTAP. Este recopilador de datos también crea un registro en el registro de la aplicación de clúster para acelerar la compatibilidad.



== Terminología

Cloud Insights adquiere datos de inventario y rendimiento a partir del recopilador de datos de ONTAP. Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para el activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Disco | Disco 


| Grupo RAID | Grupo de discos 


| Clúster | Reducida 


| Nodo | Nodo de almacenamiento 


| Agregado | Pool de almacenamiento 


| LUN | Volumen 


| Volumen | Volumen interno 
|===


== Terminología de gestión de datos ONTAP

Los siguientes términos se aplican a objetos o referencias que puede encontrar en las páginas de destino de activos de almacenamiento para la gestión de datos de ONTAP. Muchos de estos términos también se aplican a otros recopiladores de datos.



=== Reducida

* Model: Una lista delimitada por comas de los nombres de modelo de nodos discretos únicos dentro de este clúster. Si todos los nodos de los clústeres tienen el mismo tipo de modelo, solo aparecerá un nombre de modelo.
* Proveedor: El mismo nombre de proveedor que se vería si estuviera configurando un nuevo origen de datos.
* Número de serie: El número de serie de la cabina. En sistemas de almacenamiento de arquitectura en clúster como la gestión de datos de ONTAP, este número de serie puede ser menos útil que los números de serie individuales de los “nodos de almacenamiento”.
* IP: Generalmente serán las IP o los hostname tal como están configurados en el origen de datos.
* Versión de microcódigo: Firmware.
* Capacidad bruta: Suma base 2 de todos los discos físicos del sistema, sin importar su función.
* Latencia: Representación de lo que experimentan las cargas de trabajo a las que se enfrentan el host, tanto en lecturas como escrituras. Idealmente, Cloud Insights está abasteciéndose este valor directamente, pero este no es a menudo el caso. En lugar de que la cabina ofrezca esta configuración, Cloud Insights suele realizar un cálculo ponderado por IOPS derivado de las estadísticas de los volúmenes internos individuales.
* Rendimiento: Agregado de volúmenes internos. Administración: Puede contener un hipervínculo para la interfaz de gestión del dispositivo. Creado mediante programación por el origen de datos de Cloud Insights como parte de los informes de inventario.




=== Pool de almacenamiento

* Almacenamiento: En qué cabina de almacenamiento vive este pool. Obligatorio.
* Tipo: Valor descriptivo de una lista de posibilidades enumeradas. La mayoría de las veces será “agregado” o “grupo RAID”.
* Nodo: Si la arquitectura de esta cabina de almacenamiento pertenece a un nodo de almacenamiento específico, su nombre se verá aquí como un hipervínculo a su propia página de destino.
* Utiliza Flash Pool – Sí/no valor – ¿este pool basado en SATA/SAS tiene SSD utilizados para la aceleración del almacenamiento en caché?
* Redundancia: Esquema de protección o nivel de RAID. RAID_DP es de doble paridad, RAID_TP es de triple paridad.
* Capacidad: Los valores aquí son los lógicos utilizados, la capacidad utilizable y la capacidad total lógica, así como el porcentaje utilizado en estos.
* Capacidad sobreasignada: Si se utilizan tecnologías de eficiencia, se asignó una suma total de capacidades de volumen o volumen interno mayores que la capacidad lógica del pool de almacenamiento, el valor del porcentaje será mayor que 0 %.
* Snapshot: Las capacidades Snapshot se utilizan y en total, si su arquitectura de pool de almacenamiento dedica parte de su capacidad a los segmentos, en exclusiva para los snapshots. Es probable que las configuraciones de ONTAP en MetroCluster lo muestren, mientras que otras configuraciones de ONTAP son menos.
* Aprovechamiento: Un valor de porcentaje que muestra el mayor porcentaje de ocupación de disco de cualquier disco que contribuye a la capacidad de este pool de almacenamiento. El uso de discos no tiene necesariamente una fuerte correlación con el rendimiento de las cabinas. El aprovechamiento puede ser elevado debido a la recompilación de discos, a actividades de deduplicación, etc. en ausencia de cargas de trabajo dirigidas por el host. Además, las implementaciones de replicación de muchas matrices pueden impulsar el uso del disco sin mostrar como volumen interno o carga de trabajo de volumen.
* IOPS: La suma de IOPS de todos los discos que contribuyen a la capacidad de este pool de almacenamiento. Rendimiento: La suma del rendimiento de todos los discos que contribuyen a la capacidad de este pool de almacenamiento.




=== Nodo de almacenamiento

* Almacenamiento: ¿De qué cabina de almacenamiento forma parte este nodo? Obligatorio.
* Partner de ALTA DISPONIBILIDAD: En las plataformas en las que un nodo se conmuta al nodo de respaldo uno y solo otro, normalmente se verá aquí.
* Estado: Estado del nodo. Solo disponible cuando la matriz está lo suficientemente sana para ser inventariada por una fuente de datos.
* Model: Nombre de modelo del nodo.
* Versión: Nombre de versión del dispositivo.
* Número de serie: El número de serie del nodo.
* Memoria: Memoria base 2 si está disponible.
* Uso: En ONTAP, se trata de un índice de tensión de la controladora de un algoritmo propio. Con cada encuesta de rendimiento, se informará de una cifra entre 0 y 100 % que es la más alta entre la contención de disco WAFL o el uso medio de CPU. Si observa un valor sostenido > 50 %, esto indica que el dimensionamiento es insuficiente: Puede ser que una controladora/nodo no sea lo suficientemente grande o no haya suficientes discos giratorios para absorber la carga de trabajo de escritura.
* IOPS: Se deriva directamente de las llamadas ZAPI de ONTAP del objeto del nodo.
* Latencia: Se obtiene directamente de las llamadas ZAPI de ONTAP en el objeto del nodo.
* Rendimiento: Se obtiene directamente de las llamadas ZAPI de ONTAP en el objeto del nodo.
* Procesadores: Número de CPU.




== Requisitos

A continuación se enumeran los requisitos para configurar y utilizar este recopilador de datos:

* Debe tener acceso a una cuenta de administrador configurada para llamadas API de sólo lectura.
* Entre los detalles de la cuenta se incluye el nombre de usuario y la contraseña
* Requisitos del puerto: 80 o 443
* Permisos de cuenta:
+
** Nombre de función de solo lectura para la aplicación ontapi en el Vserver predeterminado
** Puede que necesite permisos de escritura opcionales adicionales. Consulte la nota sobre los permisos a continuación.


* Requisitos para la licencia de ONTAP:
+
** Se requiere una licencia FCP y volúmenes asignados/enmascarados para la detección de Fibre Channel






== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| IP de gestión de NetApp | La dirección IP o el nombre de dominio completo del clúster de NetApp 


| Nombre de usuario | Nombre de usuario del clúster de NetApp 


| Contraseña | Contraseña para el clúster de NetApp 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Tipo de conexión | Seleccione HTTP (puerto predeterminado 80) o HTTPS (puerto predeterminado 443). El valor predeterminado es HTTPS 


| Anular puerto de comunicación | Especifique un puerto diferente si no desea usar el predeterminado 


| Intervalo de sondeo de inventario (mín.) | El valor predeterminado es 60 minutos. 


| Para TLS para HTTPS | Permitir TLS sólo como protocolo cuando se utiliza HTTPS 


| Buscar automáticamente grupos de redes | Active las búsquedas automáticas de grupos de red para las reglas de directivas de exportación 


| Expansión de netgroup | Estrategia de expansión de netgroup. Seleccione _file_ o _shell_. El valor predeterminado es _shell_. 


| Tiempo de espera de lectura HTTP segundos | El valor predeterminado es 30 


| Forzar respuestas como UTF-8 | Fuerza al código del recopilador de datos para que interprete las respuestas de la CLI como en UTF-8 


| Intervalo de sondeo de rendimiento (s) | El valor predeterminado es 900 segundos. 


| Recopilación avanzada de datos de contador | Habilite la integración de ONTAP. Seleccione esta opción para incluir datos de contador avanzado de ONTAP en sondeos. Elija los contadores deseados de la lista. 
|===


== Una nota sobre los permisos

Dado que varios paneles ONTAP de Cloud Insights se basan en contadores ONTAP avanzados, debe activar *Advanced Counter Data Collection* en la sección Configuración avanzada del recopilador de datos.

También debe asegurarse de que el permiso de escritura en la API de ONTAP esté habilitado. Normalmente, esto requiere una cuenta en el nivel del clúster con los permisos necesarios.

Para crear una cuenta local para Cloud Insights en el nivel de clúster, inicie sesión en ONTAP con el nombre de usuario/contraseña del administrador de administración del clúster y ejecute los siguientes comandos en el servidor ONTAP:

. Cree un rol de solo lectura con los siguientes comandos.
+
....
security login role create -role ci_readonly -cmddirname DEFAULT -access readonly
security login role create -role ci_readonly -cmddirname security -access readonly
security login role create -role ci_readonly -access all -cmddirname “cluster application-record create”
....
. Cree el usuario de solo lectura mediante el comando siguiente. Una vez ejecutado el comando create, se le pedirá que introduzca una contraseña para este usuario.
+
 security login create -username ci_user -application ontapi -authentication-method password -role ci_readonly


Si se utiliza la cuenta AD/LDAP, el comando debería ser

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application ontapi -authentication-method domain -role ci_readonly
El rol y el inicio de sesión de usuario resultantes tendrán aspecto siguiente:

....
Role Command/ Access
Vserver Name Directory Query Level
---------- ------------- --------- ------------------ --------
cluster1 ci_readonly DEFAULT read only
cluster1 ci_readonly security readonly
....
....
cluster1::security login> show
Vserver: cluster1
Authentication Acct
UserName    Application   Method      Role Name      Locked
---------   -------      ----------- -------------- --------
ci_user     ontapi      password    ci_readonly   no
....


== Resolución de problemas

Algunas cosas para intentar si tiene problemas con este recopilador de datos:



==== Inventario

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| Recibir respuesta HTTP 401 o código de error ZAPI 13003 y ZAPI devuelve “privilegios insuficientes” o “no autorizados para este comando” | Compruebe el nombre de usuario y la contraseña, así como los privilegios y permisos de usuario. 


| La versión del clúster es < 8.1 | La versión mínima admitida del clúster es 8.1. Actualice a la versión mínima admitida. 


| ZAPI devuelve "el rol del clúster no es la LIF de gestión_clústeres" | AU necesita hablar con la IP de administración de clústeres. Compruebe la dirección IP y cambie a otra dirección IP si es necesario 


| Error: “Los servidores dedicados a almacenamiento de modo 7 no son compatibles” | Esto puede suceder si utiliza este recopilador de datos para descubrir el servidor dedicado a almacenamiento en modo 7. Cambie la IP para que apunte al clúster cdot. 


| El comando ZAPI falla después del reintento | AU tiene un problema de comunicación con el clúster. Compruebe la red, el número de puerto y la dirección IP. El usuario también debe intentar ejecutar un comando desde la línea de comandos desde la máquina AU. 


| AU no pudo conectarse a ZAPI a través de HTTP | Compruebe si EL puerto ZAPI acepta texto sin formato. Si AU intenta enviar texto sin formato a un socket SSL, la comunicación falla. 


| La comunicación falla con SSLException | AU está intentando enviar SSL a un puerto de texto sin formato de un archivador. Compruebe si EL puerto ZAPI acepta SSL o utiliza un puerto diferente. 


| Errores de conexión adicionales: La respuesta ZAPI tiene el código de error 13001, “la base de datos no está abierta” el código DE error ZAPI es 60 y la respuesta contiene “la API no terminó a tiempo” la respuesta ZAPI contiene “initialize_Session() devolvió un entorno NULL” el código DE error ZAPI es 14007 y la respuesta contiene “el nodo no está en buen estado” | Compruebe la red, el número de puerto y la dirección IP. El usuario también debe intentar ejecutar un comando desde la línea de comandos desde la máquina AU. 
|===


==== Rendimiento

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| Error de “error al recopilar el rendimiento de ZAPI” | Esto se debe normalmente a que perf stat no se está ejecutando. Pruebe el siguiente comando en cada nodo: > _system node systemshell -node * -command “spmctl -h cmd –stop; spmctl -h cmd –exec”_ 
|===
Puede encontrar información adicional en link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
