---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: Recopilador de datos IBM TotalStorage DS4000 
---
= Recopilador de datos IBM TotalStorage DS4000
:allow-uri-read: 


[role="lead"]
Este recopilador de datos adquiere información de inventario y rendimiento de los sistemas de almacenamiento IBM DS4000. Hay dos configuraciones posibles (firmware 6.x y firmware 7.x+) y ambas tienen los mismos valores.



== Terminología

Cloud Insights adquiere la siguiente información de inventario del recopilador de datos de IBM DS4000. Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Disco | Disco 


| Grupo de volúmenes | Grupo de discos 


| Cabina de almacenamiento | Reducida 


| Controladora | Nodo de almacenamiento 


| Grupo de volúmenes | Pool de almacenamiento 


| Volumen | Volumen 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* Dirección IP de cada matriz DS5 o FAStT
* Para validar el acceso, haga ping en la dirección IP de ambas controladoras de la cabina
* Requisitos del puerto: 2463




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Lista separada por comas de las IP de controladora de SANtricity de cabina | Direcciones IP y/o nombres de dominio completos para las controladoras de cabina 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | El valor predeterminado es 30 minutos 


| Intervalo de sondeo de rendimiento hasta 3600 segundos | El valor predeterminado es 300 segundos 
|===


== Resolución de problemas

Se puede encontrar información adicional sobre este colector de datos en la link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
