---
sidebar: sidebar 
permalink: task_dc_na_eseries.html 
keywords: data collector, ontap, clustered ontap 
summary: Configurar recopilador de datos E-Series de NetApp. 
---
= Recopilador de datos E-Series de NetApp
:allow-uri-read: 


[role="lead"]
El recopilador de datos de E-Series de NetApp recopila los datos de inventario y rendimiento. El recopilador admite el firmware 7.x+ usando las mismas configuraciones y informando de los mismos datos.



== Terminología

Cloud Insight adquiere la siguiente información de inventario de la colección de datos E-Series de NetApp. Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Disco | Disco 


| Grupo de volúmenes | Grupo de discos 


| Cabina de almacenamiento | Reducida 


| Controladora | Nodo de almacenamiento 


| Grupo de volúmenes | Pool de almacenamiento 


| Volumen | Volumen 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



== Terminología de E-Series (página de destino)

Los siguientes términos se aplican a objetos o referencias que puede encontrar en las páginas de destino de activos E-Series de NetApp. Muchos de estos términos también se aplican a otros recopiladores de datos.



=== Reducida

* Modelo: Nombre del modelo del dispositivo.
* Proveedor: El mismo nombre del proveedor que se vería si estaba configurando un origen de datos nuevo
* Número de serie: El número de serie de la cabina. En sistemas de almacenamiento de arquitectura en clúster como Clustered Data ONTAP de NetApp, este número de serie puede ser menos útil que los números de serie de los «nodos de almacenamiento» individuales
* IP: Generalmente serán las IP o los hostname tal como están configurados en el origen de datos
* Versión de microcódigo: Firmware
* Capacidad bruta: Suma base 2 de todos los discos físicos del sistema, sin importar su función
* Latencia: Representación de lo que experimentan las cargas de trabajo a las que se enfrentan el host, tanto en lecturas como escrituras. Idealmente, Cloud Insights está abasteciéndose este valor directamente, pero este no es a menudo el caso. En lugar de que la cabina ofrezca esta configuración, Cloud Insights suele realizar un cálculo ponderado por IOPS derivado de las estadísticas de los volúmenes individuales.
* Rendimiento: El rendimiento total de la cabina frente al host. Idealmente se obtiene directamente de la matriz, si no está disponible, Cloud Insights suma el rendimiento de los volúmenes para derivar este valor
* Administración: Puede contener un hipervínculo para la interfaz de gestión del dispositivo. Creado mediante programación por el origen de datos de Cloud Insights como parte de los informes de inventario




=== Pool de almacenamiento

* Almacenamiento: En qué cabina de almacenamiento vive este pool. Obligatorio
* Tipo: Valor descriptivo de una lista de posibilidades enumeradas. Lo más común es “Thin Provisioning” o “RAID Group”.
* Nodo: Si la arquitectura de esta cabina de almacenamiento pertenece a un nodo de almacenamiento específico, su nombre se verá aquí como un hipervínculo a su propia página de destino
* Utiliza Flash Pool – valor Sí/no
* Redundancia: Esquema de protección o nivel de RAID. E-Series informa "RAID 7" para pools DDP
* Capacidad: Los valores aquí son los lógicos utilizados, la capacidad utilizable y la capacidad total lógica, así como el porcentaje utilizado en estos. Ambos valores incluyen la capacidad de “conservación” de E-Series, lo que resulta en números y el porcentaje es superior a lo que puede mostrar la interfaz de usuario de E-Series
* Capacidad sobrecomprometida: Si, mediante tecnologías de eficiencia, se ha asignado una suma total de capacidades de volumen o volumen interno mayores que la capacidad lógica del pool de almacenamiento, el valor del porcentaje será mayor que 0 %.
* Snapshot: Las capacidades Snapshot se utilizan y en total, si su arquitectura de pool de almacenamiento dedica parte de su capacidad a los segmentos, en exclusiva para los snapshots
* Aprovechamiento: Un valor de porcentaje que muestra el mayor porcentaje de ocupación de disco de cualquier disco que contribuye a la capacidad de este pool de almacenamiento. El uso de discos no tiene necesariamente una fuerte correlación con el rendimiento de las cabinas. El aprovechamiento puede ser elevado debido a la recompilación de discos, a actividades de deduplicación, etc. en ausencia de cargas de trabajo dirigidas por el host. Además, las implementaciones de replicación de muchas matrices pueden impulsar el uso del disco sin mostrar como carga de trabajo de volumen.
* IOPS: La suma de IOPS de todos los discos que contribuyen a la capacidad de este pool de almacenamiento. Si las IOPS de disco no están disponibles en una plataforma determinada, este valor se obtendrá de la suma de las IOPS del volumen para todos los volúmenes que se encuentran en este pool de almacenamiento
* Rendimiento: La suma del rendimiento de todos los discos que contribuyen a la capacidad de este pool de almacenamiento. Si el rendimiento de disco no está disponible en una plataforma determinada, este valor se obtendrá de la suma del volumen en todos los volúmenes presentes en este pool de almacenamiento




=== Nodo de almacenamiento

* Almacenamiento: ¿De qué cabina de almacenamiento forma parte este nodo? Obligatorio
* Partner de ALTA DISPONIBILIDAD: En las plataformas en las que un nodo se conmuta al nodo de respaldo uno y solo otro, normalmente se verá aquí
* Estado: Estado del nodo. Solo disponible cuando la matriz está lo suficientemente sana para ser inventariada por una fuente de datos
* Model: Nombre de modelo del nodo
* Versión: Nombre de versión del dispositivo.
* Número de serie: El número de serie del nodo
* Memoria: Memoria base 2 si está disponible
* Utilización: Normalmente un número de utilización de CPU o, en el caso de ONTAP de NetApp, un índice de estrés de la controladora. Actualmente, la utilización no está disponible para E-Series de NetApp
* IOPS: Número que representa el número de IOPS dirigido por el host en esta controladora. Lo ideal es que se genere directamente desde la cabina y, si no está disponible, se calculará sumando todos los IOPS de los volúmenes que pertenecen exclusivamente a este nodo.
* Latencia: Un número que representa la latencia del host o el tiempo de respuesta típicos de esta controladora. Lo ideal es que se genere directamente desde la cabina y, si no está disponible, se calculará realizando un cálculo de IOPS ponderado a partir de volúmenes que pertenecen de manera exclusiva a este nodo.
* Rendimiento: Un número que representa el rendimiento impulsado por el host en esta controladora. Lo ideal es que se genere directamente desde la cabina, si no está disponible, se calculará sumando todo el rendimiento de los volúmenes que pertenecen exclusivamente a este nodo.
* Procesadores: Número de CPU




== Requisitos

* La dirección IP de cada controladora de la cabina
* Requisito de puerto 2463




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Lista separada por comas de las IP de controladora de SANtricity de cabina | Direcciones IP y/o nombres de dominio completos para las controladoras de cabina 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | El valor predeterminado es 30 minutos 


| Intervalo de sondeo de rendimiento hasta 3600 segundos | El valor predeterminado es 300 segundos 
|===


== Resolución de problemas

Puede encontrar información adicional sobre este recopilador de datos en link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
