---
sidebar: sidebar 
permalink: task_dc_emc_datadomain.html 
keywords: data collector, Data Domain, EMC, DELL 
summary: Configuración del recopilador DE datos DE DELL EMC Data Domain. 
---
= Recopilador DE datos DE DELL EMC Data Domain
:allow-uri-read: 


[role="lead"]
Este recopilador de datos recopila información de inventario y rendimiento de los sistemas DE almacenamiento DE deduplicación DE Dell EMC Data Domain. Para configurar este recopilador de datos, hay instrucciones de configuración específicas y recomendaciones de uso que debe seguir.



== Terminología

Cloud Insights adquiere la siguiente información de inventario del recopilador de datos de Data Domain. Para cada tipo de activo adquirido por Cloud Insights, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Disco | Disco 


| Cabina | Reducida 


| Puerto FC | Puerto 


| Sistema de archivos | Volumen interno 


| Cuota | Cuota 


| Unidades NFS y CIFS | Fileshare 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este colletor de datos.



== Requisitos

Necesita la siguiente información para configurar este recopilador de datos:

* Dirección IP del dispositivo Data Domain
* Nombre de usuario y contraseña de sólo lectura para el almacenamiento de Data Domain
* Puerto SSH 22




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP | La dirección IP o el nombre de dominio completo de la cabina de almacenamiento Data Domain 


| Nombre de usuario | El nombre de usuario para la cabina de almacenamiento Data Domain 


| Contraseña | La contraseña de la cabina de almacenamiento de Data Domain 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | Intervalo entre sondeos de inventario. El valor predeterminado es 20. 


| Puerto SSH | Puerto del servicio SSH 
|===


== Resolución de problemas

Se puede encontrar información adicional sobre este colector de datos en la link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
