---
sidebar: sidebar 
permalink: task_dc_ms_anf.html 
keywords: data collector, azure, Netapp files, anf 
summary: Configurar el recopilador de datos de Azure NetApp Files. 
---
= Configurar el recopilador de datos de Azure NetApp Files
:allow-uri-read: 


[role="lead"]
Cloud Insights utiliza el recopilador de datos de Azure NetApp Files para adquirir datos de inventario y rendimiento.



== Requisitos

Necesita la siguiente información para configurar este recopilador de datos.

* Requisito de puerto: 443 HTTPS
* IP de REST de Azure Management (management.azure.com)
* ID del cliente principal del servicio Azure (cuenta de usuario)
* Clave de autenticación principal del servicio Azure (contraseña de usuario)
* Debe configurar una cuenta de Azure para la detección de Cloud Insights.
+
Una vez que la cuenta se haya configurado correctamente y registre la aplicación en Azure, tendrá las credenciales necesarias para descubrir la instancia de Azure con Cloud Insights. En el siguiente enlace se describe cómo configurar la cuenta para la detección:



https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]



== Configuración

Introduzca los datos en los campos del recopilador de datos de acuerdo con la tabla siguiente:

[cols="2*"]
|===
| Campo | Descripción 


| ID del cliente principal del servicio Azure | ID de inicio de sesión en Azure 


| ID de inquilino de Azure | ID de inquilino de Azure 


| Clave de autenticación principal del servicio Azure | Clave de autenticación de inicio de sesión 


| Entiendo que Microsoft me factura por las solicitudes de API | Marque esto para verificar que Microsoft le da la cuenta de las solicitudes de API que ha realizado el sondeo de Insight. 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | El valor predeterminado es 60 
|===


== Resolución de problemas

* Las credenciales utilizadas por el recopilador de datos ANF no deben tener acceso a ninguna suscripción de Azure que contenga volúmenes ANF.
* Si el acceso de Reader provoca un error en la recopilación de rendimiento, intente conceder acceso de colaborador en un nivel de grupo de recursos.


Se puede encontrar información adicional sobre este colector de datos en la link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
