---
sidebar: sidebar 
permalink: task_cs_add_collector_ontap.html 
keywords: data collector, ONTAP, SVM 
summary: Adición de recopiladores de datos 
---
= Configuración del recopilador de datos de ONTAP de NetApp
:allow-uri-read: 


[role="lead"]
Cloud Secure utiliza recopiladores de datos para recopilar datos de acceso de archivos y usuarios desde dispositivos. Los datos se proporcionan a Cloud Secure para su análisis.

.Antes de empezar
Necesita la siguiente información para configurar este recopilador de datos:

* Se debe configurar un agente para recopilar datos
* La dirección IP de gestión de SVM
* Un nombre de usuario para acceder a la SVM
* La contraseña para acceder a la SVM


.Pasos para la configuración
. Inicie sesión como administrador o propietario de cuenta en su entorno de Cloud Secure.
. Haga clic en *Admin > colectores de datos > +colectores de datos*
+
El sistema muestra los colectores de datos disponibles.

. Haga clic en *+Monitor* en el icono NetApp ONTAP.
+
El sistema muestra la página de configuración de la SVM Add Data Collector: ONTAP.

. Introduzca un nombre único para el recopilador
. Seleccione el agente que recogerá los datos
. Introduzca la dirección IP de gestión de la SVM
. Introduzca el nombre de usuario para acceder a la SVM
. Introduzca la contraseña para acceder a la SVM
. Haga clic en *+Agregar colector*


.Después de terminar
* Haga clic en *Admin > colectores de datos* para comprobar el estado del recopilador configurado.
+
Normalmente hay un retraso antes de que se muestre el estado del recopilador.


