---
sidebar: sidebar 
permalink: task_config_telegraf_dcos.html 
keywords: telegraf, installation, install, dcos 
summary: configuración de dcos 
---
= Recopilador de datos de DC/OS
:allow-uri-read: 


[role="lead"]
Cloud Insights utiliza este recopilador de datos para recopilar métricas de DC/OS.



== Instalación

. En *Admin > colectores de datos*, haga clic en *+colector de datos*. En *Servicios*, elija *DC/OS*.
+
Si no ha configurado un agente para la colección, se le pedirá que lo haga link:task_config_telegraf_agent.html["instale un agente"] en su entorno.

+
Si ya ha configurado un agente, seleccione el sistema operativo o la plataforma adecuados y haga clic en *continuar*.

. Siga las instrucciones de la pantalla Configuración de DC/OS para configurar el recopilador de datos. Las instrucciones varían en función del tipo de sistema operativo o plataforma que utilice para recopilar datos.




== Configuración

La información de configuración se puede encontrar en https://docs.mesosphere.com["Documentación de DC/OS"].



== Objetos y contadores

Se recopilan los objetos siguientes y sus contadores:

[cols="<.<,<.<,<.<,<.<"]
|===
| Objeto | Identificadores | Atributos | Puntos de datos 


| dcos_node | dcos_container dcos_app | ruta de nombre de host del clúster (solo campos del sistema de archivos) interfaz (solo campos de red) container_id task_name | system_uptime (float) cpu_núcleos (float) cpu_total (float) cpu_user (float) cpu_system (float) cpu_idle (float) cpu_wait (float) load_1min (float) ( float) int_int_int_memory_int_int) ( total_swing_bytes) roat_int_int_memory) (swing_int_int_int_int) bytes) (swing_int_int_int_reint_memory) (valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_valor_de_de_de_de_de_de_de_de_de_de_de_de_de_de_de_de_de_de_de_de_es) network_in_packets (float) network_out_packets (float) network_in_dropped (float) network_out_dropped (float) network_in_errors (float) network_out_errors (float) process_count (float) 
|===


== Resolución de problemas

Puede encontrar información adicional en la link:concept_requesting_support.html["Soporte técnico"] página.
