---
sidebar: sidebar 
permalink: task_dc_na_solidfire.html 
summary: Configurar recopilador de datos de SolidFire de NetApp 
keywords: data collector, queries, create 
---
= Recopilador de datos de cabinas all-flash SolidFire de NetApp
:allow-uri-read: 


[role="lead"]
El recopilador de datos de la cabina all-flash SolidFire de NetApp admite la recogida de inventario y rendimiento de las configuraciones de SolidFire de iSCSI y Fibre Channel.

El recopilador de datos de SolidFire utiliza la API DE REST de SolidFire. La unidad de adquisición en la que reside el recopilador de datos debe poder iniciar conexiones HTTPS con el puerto TCP 443 de la dirección IP de administración del clúster SolidFire. El recopilador de datos necesita credenciales para realizar consultas de API DE REST en el clúster de SolidFire.



== Terminología

Cloud Insights adquiere la siguiente información de inventario de la colección de datos de cabinas all-flash SolidFire de NetApp. Para cada tipo de activo adquirido por Cloud Insights, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Unidad | Disco 


| Clúster | Reducida 


| Nodo | Nodo de almacenamiento 


| Volumen | Volumen 


| Puerto Fibre Channel | Puerto 


| Grupo de acceso de volúmenes, asignación de LUN | Asignación de volumen 


| Sesión iSCSI | Máscara de volumen 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

A continuación se indican los requisitos para configurar este recopilador de datos:

* Dirección IP virtual de gestión
* Nombre de usuario y credenciales de solo lectura
* Puerto 443




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP virtual de gestión (MVIP) | La dirección IP virtual de gestión del clúster de SolidFire 


| Nombre de usuario | Nombre que se utiliza para iniciar sesión en el clúster SolidFire 


| Contraseña | La contraseña que se utiliza para iniciar sesión en el clúster de SolidFire 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Tipo de conexión | Elija el tipo de conexión 


| Puerto de comunicación | Puerto que se utiliza para la API de NetApp 


| Intervalo de sondeo de inventario (mín.) | El valor predeterminado es 20 minutos 


| Intervalo de sondeo de rendimiento (s) | El valor predeterminado es 300 segundos 
|===


== Resolución de problemas

Cuando SolidFire informa de un error, se muestra en Cloud Insights de la siguiente manera:

_Se ha recibido un mensaje de error de un dispositivo SolidFire al intentar recuperar datos. La llamada era <method> (<parameterString>). El mensaje de error del dispositivo era (consulte el manual del dispositivo): <message>_

Donde:

* <method> es un método HTTP, como GET o PUT.
* <parameterString> es una lista separada por comas de parámetros que se incluyeron en LA llamada DE DESCANSO.
* El <message> es lo que el dispositivo devolvió como mensaje de error.


Se puede encontrar información adicional sobre este colector de datos en la link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
