---
sidebar: sidebar 
permalink: task_dc_emc_xio.html 
keywords: data collector, XtremeIO, EMC 
summary: Configuración del recopilador de datos de XtremeIO. 
---
= Recopilador de datos de Dell EMC XtremeIO
:allow-uri-read: 


[role="lead"]
El recopilador de datos de EMC XtremIO adquiere los datos de inventario y rendimiento del sistema de almacenamiento XtremIO de EMC.



== Requisitos

Para configurar el recopilador de datos de EMC XtremIO (HTTP), debe tener:

* La dirección del host de XtremIO Management Server (XMS)
* Una cuenta con privilegios de administrador
* Acceso al puerto 443 (HTTPS)




== Terminología

Cloud Insights adquiere la siguiente información de inventario del recopilador de datos de EMC XtremIO. Para cada tipo de activo adquirido por Cloud Insights, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este origen de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Disco (SSD) | Disco 


| Clúster | Reducida 


| Controladora | Nodo de almacenamiento 


| Volumen | Volumen 


| Mapa de LUN | Asignación de volumen 


| Iniciador FC de destino | Máscara de volumen 
|===
Nota: Sólo se trata de asignaciones terminológicas comunes y es posible que no representen todos los casos de este origen de datos.



== Requisitos

* La dirección IP del host de XtremIO Management Server (XMS)
* Nombre de usuario y contraseña de administrador para XtremIO




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Host XMS | La dirección IP o el nombre de dominio completo de XtremIO Management Server 


| Nombre de usuario | Nombre de usuario del servidor de gestión de XtremIO 


| Contraseña | Contraseña del servidor de gestión de XtremIO 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Puerto TCP | Puerto TCP utilizado para conectar con el servidor de administración XTremIO. El valor predeterminado es 443. 


| Intervalo de sondeo de inventario (min) | Intervalo entre sondeos de inventario. El valor predeterminado es 60 minutos. 


| Intervalo de sondeo de rendimiento (s) | Intervalo entre sondeos de rendimiento. El valor predeterminado es 300 segundos. 
|===


== Resolución de problemas

Se puede encontrar información adicional sobre este colector de datos en la link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
