---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: Se crean reglas de anotación para aplicar anotaciones automáticamente a varios activos. 
---
= Creación de reglas de anotación
:allow-uri-read: 


[role="lead"]
Puede utilizar reglas de anotación para aplicar anotaciones automáticamente a varios activos basándose en los criterios definidos. Cloud Insights asigna las anotaciones a los activos basándose en estas reglas. Las anotaciones definidas manualmente en una página de activos individual tienen prioridad sobre las anotaciones basadas en reglas cuando Cloud Insight evalúa las reglas de anotación.

.Antes de empezar
Debe haber creado una consulta para la regla de anotación.

.Pasos
. En el menú Cloud Insights, haga clic en *Administrar > Reglas de anotación*.
. Haga clic en *+ Regla* para agregar una nueva regla de anotación.
+
Aparecerá el cuadro de diálogo Agregar regla.

. Haga lo siguiente:
+
.. En el cuadro *Nombre*, escriba un nombre único que describa la regla.
+
El nombre aparece en la página Reglas de anotación.

.. Haga clic en *Consulta* y seleccione la consulta que Cloud Insights utiliza para identificar los activos a los que se aplica la anotación.
.. Haga clic en *anotación* y seleccione la anotación que desea aplicar.
.. Haga clic en *valor* y seleccione un valor para la anotación.
+
Por ejemplo, si selecciona Cumpleaños como anotación, especifique una fecha para el valor.

.. Haga clic en *Guardar*
.. Haga clic en *Ejecutar todas las reglas* si desea ejecutar todas las reglas inmediatamente; de lo contrario, las reglas se ejecutarán a un intervalo programado regularmente.
+

NOTE: En un entorno Cloud Insights grande, puede observar que la ejecución de reglas de anotación parece tardar un tiempo en completarse. Esto se debe a que el indexador se ejecuta primero y debe completarse antes de ejecutar las reglas. El indizador es lo que proporciona a Cloud Insights la posibilidad de buscar o filtrar objetos y contadores nuevos o actualizados en sus datos. El motor de reglas espera hasta que el indexador complete su actualización antes de aplicar las reglas.







== Modificación de reglas de anotación

Puede modificar una regla de anotación para cambiar el nombre de la regla, su anotación, el valor de la anotación o la consulta asociada con la regla.

.Pasos
. En el menú Cloud Insights, haga clic en *Administrar > Reglas de anotación*.
+
La página Reglas de anotación muestra la lista de reglas de anotación existentes.

. Busque la regla de anotación que desea modificar.
+
Puede filtrar las reglas de anotación introduciendo un valor en el cuadro de filtro o haciendo clic en un número de página para examinar las reglas de anotación por página.

. Haga clic en el icono de menú de la regla que desea modificar.
. Haga clic en *Editar*
+
Se mostrará el cuadro de diálogo Editar regla.

. Modifique el nombre, la anotación, el valor o la consulta de la regla de anotación.




== Cambio del orden de las reglas

Las reglas de anotación se procesan desde la parte superior de la lista de reglas hasta la parte inferior. Para cambiar el orden en que se procesa una regla, haga lo siguiente:

.Pasos
. Haga clic en el icono de menú de la regla que desea mover.
. Haga clic en *Subir* o en *bajar* según sea necesario hasta que la regla aparezca en la ubicación que desee.




== Eliminación de reglas de anotación

Es posible que desee eliminar reglas de anotación que ya no se utilicen.

.Pasos
. En el menú Cloud Insights, haga clic en *Administrar > Reglas de anotación*.
+
La página Reglas de anotación muestra la lista de reglas de anotación existentes.

. Busque la regla de anotación que desea eliminar.
+
Puede filtrar las reglas de anotación introduciendo un valor en el cuadro de filtro o haciendo clic en un número de página para examinar las reglas de anotación por página.

. Haga clic en el icono de menú de la regla que desea eliminar.
. Haga clic en *Eliminar*
+
Aparecerá un mensaje de confirmación en el que se le preguntará si desea eliminar la regla.

. Haga clic en *Aceptar*

