---
sidebar: sidebar 
permalink: task_defining_annotations.html 
keywords: annotations, monitor, notes, tags 
summary: Realizar un seguimiento de los datos mediante anotaciones. 
---
= Definición de anotaciones
:allow-uri-read: 


[role="lead"]
A la hora de personalizar Cloud Insights para realizar un seguimiento de los datos según sus requisitos corporativos, puede definir notas especializadas, llamadas anotaciones y asignarlas a sus activos.

Puede asignar anotaciones a activos con información como la finalización de la vida útil de los activos, el centro de datos, la ubicación de creación, el nivel de almacenamiento o el nivel de servicio de volumen.

El uso de anotaciones para supervisar su entorno incluye las siguientes tareas de alto nivel:

* Crear o editar definiciones para todos los tipos de anotaciones.
* Mostrar páginas de activos y asociar cada activo con una o varias anotaciones.
+
Por ejemplo, si un activo se está arrendando y el arrendamiento caduca dentro de dos meses, puede que desee aplicar una anotación de fin de vida al activo. Esto ayuda a evitar que otros utilicen ese activo durante un tiempo prolongado.

* Crear reglas para aplicar anotaciones automáticamente a varios activos del mismo tipo.
* Filtrar activos por sus anotaciones.




== Tipos de anotaciones predeterminados

Cloud Insights proporciona algunos tipos de anotaciones predeterminados. Estas anotaciones pueden utilizarse para filtrar o agrupar datos.

Puede asociar activos con tipos de anotación predeterminados como los siguientes:

* Ciclo de vida de los activos, como cumpleaños, puesta de sol o fin de vida
* Información sobre la ubicación de un dispositivo, como un centro de datos, un edificio o un piso
* Clasificación de activos, como por calidad (niveles), por dispositivos conectados (nivel de switch) o por nivel de servicio
* Estado, como caliente (alta utilización)


En la siguiente tabla se enumeran los tipos de anotación proporcionados por Cloud Insights.

[cols="30,53, 16"]
|===


| Tipos de anotaciones | Descripción | Tipo 


| Alias | Nombre sencillo para un recurso | Texto 


| Grupo de recursos informáticos | Asignación de grupos utilizada por el recopilador de datos de sistemas de archivos del host y el equipo virtual | Lista 


| Centro de datos | Ubicación física | Lista 


| Caliente | Dispositivos de uso intensivo de forma regular o en el umbral de capacidad | Booleano 


| Nota | Comentarios asociados a un recurso | Prueba 


| Nivel de servicio | Un conjunto de niveles de servicio compatibles que puede asignar a recursos. Proporciona una lista de opciones ordenadas para volúmenes internos, qtrees y volúmenes. Editar niveles de servicio para establecer políticas de rendimiento para diferentes niveles. | Lista 


| Puesta de sol | Límite establecido después del cual no se puede realizar ninguna asignación nueva a ese dispositivo. Útil para migraciones planificadas y otros cambios de red pendientes. | Fecha 


| Cambiar el nivel | Opciones predefinidas para configurar categorías para conmutadores. Normalmente, estas designaciones permanecen durante toda la vida útil del dispositivo, aunque puede editarlas. Sólo disponible para interruptores. | Lista 


| Nivel | Puede utilizarse para definir distintos niveles de servicio dentro de su entorno. Los niveles pueden definir el tipo de nivel, como la velocidad necesaria (por ejemplo, oro o plata). Esta función solo está disponible en volúmenes internos, qtrees, cabinas de almacenamiento, pools de almacenamiento y volúmenes. | Lista 


| Gravedad de la infracción | Clasificación (por ejemplo, mayor) de una infracción (por ejemplo, falta de puertos de host o falta de redundancia), en una jerarquía de mayor a menor importancia. | Lista 
|===

NOTE: Alias, centro de datos, caliente, nivel de servicio, puesta de sol, El nivel de cambio, el nivel y la gravedad de la infracción son anotaciones a nivel de sistema, que no puede eliminar ni cambiar de nombre; sólo puede cambiar sus valores asignados.



== Creación de anotaciones personalizadas

Con las anotaciones, puede agregar datos personalizados específicos del negocio que se ajusten a los activos de las necesidades del negocio. Aunque Cloud Insights proporciona un conjunto de anotaciones predeterminadas, es posible que desee ver datos de otras maneras. Los datos de anotaciones personalizadas complementan los datos del dispositivo ya recopilados, como el fabricante de almacenamiento, los volúmenes de número y las estadísticas de rendimiento. Cloud Insights no detecta los datos que se agregan con anotaciones.

.Pasos
. En el menú Cloud Insights, haga clic en *Administrar > Anotaciones*.
+
La página Anotaciones muestra la lista de anotaciones.

. Haga clic en *+Agregar*
. Introduzca un *Nombre* y *Descripción* de la anotación.
+
Es posible introducir hasta 255 caracteres en estos campos.

. Haga clic en *Tipo* y, a continuación, seleccione una de las siguientes opciones que representa el tipo de datos permitidos en esta anotación:


.Tipos de anotaciones
Booleano:: Crea una lista desplegable con las opciones yes y no Por ejemplo, la anotación "Conexión directa" es booleana.
Fecha:: Esto crea un campo que contiene una fecha. Por ejemplo, si la anotación será una fecha, selecciónela.
Lista:: Crea una de las siguientes opciones:
+
--
* Una lista desplegable fija
+
Cuando otros están asignando este tipo de anotación en un dispositivo, no pueden agregar más valores a la lista.

* Una lista desplegable flexible
+
Si selecciona la opción Agregar nuevos valores sobre la marcha al crear esta lista, cuando otros están asignando este tipo de anotación en un dispositivo, pueden agregar más valores a la lista.



--
Número:: Crea un campo en el que el usuario que asigna la anotación puede introducir un número. Por ejemplo, si el tipo de anotación es "planta", el usuario puede seleccionar el tipo de valor "número" e introducir el número de planta.
Texto:: Crea un campo que permite texto de formato libre. Por ejemplo, puede escribir "Idioma" como tipo de anotación, seleccionar "texto" como tipo de valor e introducir un idioma como valor.



NOTE: Después de establecer el tipo y guardar los cambios, no puede cambiar el tipo de anotación. Si necesita cambiar el tipo, debe eliminar la anotación y crear una nueva.

. Si selecciona Lista como tipo de anotación, haga lo siguiente:
+
.. Seleccione *Agregar nuevos valores sobre la marcha* si desea la capacidad de agregar más valores a la anotación cuando se encuentra en una página de activos, que crea una lista flexible.
+
Por ejemplo, supongamos que se encuentra en una página de activos y que el activo tiene la anotación Ciudad con los valores Detroit, Tampa y Boston. Si ha seleccionado la opción *Agregar nuevos valores sobre la marcha*, puede agregar valores adicionales a Ciudad como San Francisco y Chicago directamente en la página de activos en lugar de tener que ir a la página Anotaciones para agregarlos. Si no selecciona esta opción, no podrá agregar nuevos valores de anotación al aplicar la anotación; esto creará una lista fija.

.. Introduzca un valor y una descripción en los campos *valor* y *Descripción*.
.. Haga clic en *+Add+* para agregar valores adicionales.
.. Haga clic en el icono Papelera para eliminar un valor.


. Haga clic en *Guardar*
+
Las anotaciones aparecen en la lista de la página Anotaciones.



.Después de terminar
En la interfaz de usuario, la anotación está disponible inmediatamente para su uso.
