---
sidebar: sidebar 
permalink: task_dc_na_astra_data_store.html 
summary: Configurar el almacén de datos Astra de NetApp 
keywords: data collector, queries, create, astra, data, store, 
---
= Recopilador de datos de NetApp Astra Data Store
:allow-uri-read: 


[role="lead"]
Este recopilador de datos adquiere datos de inventario y rendimiento para un único clúster de almacén de datos de Astra. Además del recopilador de datos, el operador de monitorización configurará _Telegraf_ para recopilar métricas avanzadas y _Fluent bit_ para recopilar registros.


TIP: Estas instrucciones de instalación e información adicional también se encuentran en la documentación de Astra Data Store:link:https://docs.netapp.com/us-en/astra-data-store/use/monitor-with-cloud-insights.html["Supervisar métricas con Cloud Insights"]
link:https://docs.netapp.com/us-en/astra-data-store/get-started/quick-start.html["Inicio rápido de Astra Data Store"]



== Terminología

Cloud Insights adquiere datos de inventario y rendimiento de este recopilador de datos. Para cada tipo de activo adquirido, se muestra la terminología más común utilizada para el activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| AstrAstrDSVolume | Volumen interno 


| AstroDSNodeInfo.status.drives | Disco 


| AstrDSNodeInfo | Nodo de almacenamiento 


| AstrakSExportPolicy | Compartir / Compartir iniciador 


| AstrakCluster | Reducida 
|===


== Requisitos

* Debe instalarse el operador de supervisión de NetApp en el clúster de Kubernetes con Astra Data Store. Si no se instaló durante la instalación de Astra Data Store, instale el operador de monitorización siguiendo las instrucciones de instalación de Astra Data Store.
* Se debe instalar el complemento _kubectl-astrads_ kubectl. Si no está instalado, instale el binario _kubectl-astrads_ siguiendo las instrucciones de instalación de Astra Data Store.
* Los siguientes comandos deben estar disponibles: _Awk, curl, grep y jq_.




== Instalación

La secuencia de comandos de instalación le guiará por la instalación del recopilador de datos de Astra Data Store. Siga las instrucciones que aparecen en pantalla. La instalación tardará varios minutos en completarse. Una vez finalizada, puede tardar varios minutos antes de que los datos se muestren en Cloud Insights.

La secuencia de comandos le guiará por los siguientes pasos:

. Elija un token de acceso a la API.
. Copie la secuencia de comandos del instalador del cuadro de diálogo de instalación y guárdela como un archivo denominado _cloudadreads-Monitoring.sh_. Puede hacer clic en el icono del portapapeles para copiar la secuencia de comandos rápidamente en el portapapeles.
. Abra una ventana Bash, cambie el directorio a la ubicación del script _cloudaeareas-ADS-Monitoring.sh_.
. Copie el bloque de comandos de permisos del cuadro de diálogo de instalación. Puede hacer clic en el icono del portapapeles para copiar rápidamente el comando en el portapapeles.
. Pegue el comando permisos en la ventana Bash y pulse Intro.
. Copie el comando install del cuadro de diálogo de instalación. Puede hacer clic en el icono del portapapeles para copiar rápidamente el comando en el portapapeles.
. Pegue el comando install en la ventana Bash.
. Reemplace <KUBERNETES_IP> por la dirección IP del servidor API de Kubernetes.
. Sustituya <KUBERNETES_TOKEN> por su token de API de Kubernetes.
. Pulse Intro.
+
La secuencia de comandos del instalador: * Verifique que el operador de supervisión esté instalado y configurado. * Configure Fluent Bit. * Configurar Telegraf. * Instale la unidad de adquisición. * Instale el recopilador Astra Data Store una vez que la unidad de adquisición esté en funcionamiento.

. Haga clic en _Complete Setup_.


Si la secuencia de comandos del instalador se sale debido a un error, puede volver a ejecutarlo una vez resuelto el error. La secuencia de comandos del instalador admite parámetros adicionales como el espacio de nombres del operador de supervisión y el puerto del servidor de la API de Kubernetes si su entorno no utiliza los ajustes predeterminados. A continuación se muestra una lista completa de las opciones disponibles.



=== Opciones del script del instalador:

Tenga en cuenta que el nombre de dominio de Cloud Insights y la clave de acceso de API seleccionada se incrustarán en la secuencia de comandos del instalador cuando se descargue.

....
$ ./cloudinsights-ads-monitoring.sh -h
USAGE: cloudinsights-ads-monitoring.sh [OPTIONS]
Configure monitoring of Astra Data Store by Cloud Insights.
OPTIONS:
 -h                      Display this help message.
 -d ci_domain_name       Cloud Insights tenant domain name.
 -i kubernetes_ip        Kubernetes API server IP address.
 -k ci_api_key           Cloud Insights API Access Key.
 -n namespace            Namespace for monitoring components. (default: netapp-monitoring)
 -p kubernetes_port      Kubernetes API server port. (default: 6443)
 -r root_pv_dir          Create 3 Persistent Volumes in this directory for the Acquisition Unit.
                         Only specify this option if there is no Storage Provisioner installed and the PVs do not already exist.
 -s storage_class        Storage Class name for provisioning Acquisition Unit PVs. If not specified, the default storage class will be used.
 -t kubernetes_token     Kubernetes API server token.
....


== Resolución de problemas

Algunas cosas para intentar si tiene problemas con este recopilador de datos:



==== Recopilador de datos de Astra Data Store

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| Usted ve un mensaje "no autorizado" | Compruebe que el token de API de Kubernetes tenga permiso para llamar a las API en el apiGroup _astrads.netapp.io_ 


| "Host desconocido: Astrads-Metrics-service.astrads-system.svc.cluster.local: Nombre o servicio no conocido" | Compruebe que el recopilador esté instalado en un pod de la unidad de adquisición que se ejecuta dentro del clúster DE Kubernetes DE ADS. Compruebe que el servicio astrads-Metrics está ejecutando el espacio de nombres astrads-system. 
|===


==== Secuencia de comandos de instalación

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| El operador de supervisión no se está ejecutando en el espacio de nombres de <namespace>. | Siga las instrucciones de instalación de Astra Data Store para instalarla 


| La unidad de adquisición Pod <pod> no se inició correctamente después de 300 segundos. | Obtenga el nombre del pod de la unidad de adquisición: Kubectl get pods --namespace netapp-Monitoring | grep "au-pod"; revise los eventos del pod en busca de errores: Kubectl describa pod --Namespace <POD_NAME> de supervisión de netapp 


| La instalación de la unidad de adquisición no ha finalizado después de 900 segundos | Obtenga el nombre del pod de la unidad de adquisición: Kubectl get pods --namespace netapp-Monitoring | grep "au-pod"; compruebe los registros en pod en busca de errores: Kubectl logs -- Espacio de nombres <POD_NAME> de supervisión de netapp Si no hay errores y los registros terminan con el mensaje "Principal - adquisición está activa y en ejecución!", la instalación se ha realizado correctamente pero es más larga de lo esperado. Vuelva a ejecutar el script de instalación. 


| Error al recuperar el ID de unidad de adquisición de Cloud Insights | Compruebe que la unidad de adquisición aparece en Cloud Insights. Vaya a Admin > colectores de datos y haga clic en la pestaña unidades de adquisición. Compruebe que la clave de API de Cloud Insights tiene permiso para la unidad de adquisición. 
|===
Se puede encontrar información adicional sobre este colector de datos en la link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
