---
sidebar: sidebar 
permalink: task_config_cs_amazon_fsx.html 
keywords: Cloud, Storage, AWS, Fsx 
summary: Cloud Secure utiliza recopiladores de datos para recopilar datos de acceso de archivos y usuarios desde dispositivos. 
---
= Configuración de Amazon FSX para ONTAP de NetApp
:allow-uri-read: 


[role="lead"]
Este recopilador de datos recopila los datos de acceso de usuario y archivos de Amazon FSX para ONTAP de NetApp. Este recopilador de datos estará disponible de forma incremental en todas las regiones de servicio de Cloud Insights. Póngase en contacto con su representante de ventas si no ve el icono de este recopilador en su entorno de Cloud Insights.



=== Configuración de máquina de agente

Siga estos pasos para configurar el equipo que se utilizará como agente de Cloud Secure:

. Inicie sesión en la consola de AWS y desplácese a la página EC2-instance y seleccione Launch instance.
. Seleccione un RHEL o CentOS AMI con la versión adecuada como se indica en el link:concept_cs_agent_requirements.html["Requisitos"].
. Cree el cuadro Agente en el mismo VPC y subred en que resida la instancia de Amazon FSX para ONTAP de NetApp.
+
O el recuadro Agent debe estar en un VPC que disponga de conectividad a Amazon FSX para ONTAP VPC de NetApp.

+
Asegúrese de que existe la comunicación bidireccional entre el agente y Amazon FSX para ONTAP de NetApp.

. Seleccione t2.xlarge (4 vcpu y 16 GB de RAM) como recursos asignados.
+
.. Cree la instancia de EC2.


. Instale los paquetes de Linux necesarios con el gestor de paquetes YUM:
+
.. Instale wget y descomprima los paquetes Linux nativos.






=== Instale el agente de Cloud Secure

. Inicie sesión como administrador o propietario de cuenta en su entorno de Cloud Insights.
. Vaya a Administración de Cloud Secure > colectores de datos y haga clic en la ficha agentes.
. Haga clic en +Agent y especifique RHEL como plataforma de destino.
. Copie el comando instalación del agente.
. Pegue el comando Agent Installation en la instancia de RHEL EC2 en la que ha iniciado sesión.
+
De esta forma se instala el agente Cloud Secure, siempre que se cumplan todos los requisitos previos del agente.



Para conocer los pasos detallados, consulte el Cloud Secure link:task_cs_add_agent.html["Instalación del agente"] página,
