---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: Configuración del recopilador DE datos DE DELL EMC Celerra. 
---
= Recopilador DE datos DE DELL EMC VNX File (anteriormente Celerra Unified Storage System)
:allow-uri-read: 


[role="lead"]
Este recopilador de datos adquiere información de inventario de VNX File Storage System. Para la configuración, este recopilador de datos requiere la dirección IP de los procesadores de almacenamiento y un nombre de usuario y contraseña de sólo lectura.



== Terminología

Cloud Insights adquiere la siguiente información de inventario del recopilador de datos de VNX. Para cada tipo de activo adquirido por Cloud Insights, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Servidor de red Celerra/pool de almacenamiento Celerra | Pool de almacenamiento 


| Sistema de archivos | Volumen interno 


| Transmisor de datos | Controladora 


| Sistema de archivos montado en un transportador de datos | Recurso compartido de archivos 


| Exportaciones CIFS y NFS | Share 


| Volumen de disco | LUN back-end 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

Necesita lo siguiente para configurar este recopilador de datos:

* La dirección IP del procesador de almacenamiento
* Nombre de usuario y contraseña de solo lectura
* Puerto SSH 22




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP de archivo VNX | Dirección IP o nombre de dominio completo del dispositivo VNX File 


| Nombre de usuario | Nombre utilizado para iniciar sesión en el dispositivo VNX File 


| Contraseña | Contraseña utilizada para iniciar sesión en el dispositivo VNX File 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (minutos) | Intervalo entre sondeos de inventario. El valor predeterminado es 20 minutos. 
|===


== Resolución de problemas

Algunas cosas para intentar si tiene problemas con este recopilador de datos:



==== Inventario

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| Error: No se puede continuar mientras la actualización DART está en curso | Solución posible: Detenga el recopilador de datos y espere a que finalice la actualización de DART antes de intentar otra solicitud de adquisición. 
|===
Puede encontrar información adicional en link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
