---
sidebar: sidebar 
permalink: task-planning-your-config.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, ec2, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, general purpose, gp2 provisioned IOPS, piops, throughput optimized, cold, SSD, HDD, st1, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported instances, instances, instances supported, supported ec2 instances, supported instance, aws outpost, outpost, outposts, deploy in outpost, deploy in aws outpost 
summary: Al poner en marcha Cloud Volumes ONTAP en AWS, puede elegir un sistema preconfigurado que se ajuste a los requisitos de la carga de trabajo, o bien puede crear su propia configuración. Si elige su propia configuración, debe conocer las opciones disponibles. 
---
= Planifique la configuración de Cloud Volumes ONTAP en AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Al poner en marcha Cloud Volumes ONTAP en AWS, puede elegir un sistema preconfigurado que se ajuste a los requisitos de la carga de trabajo, o bien puede crear su propia configuración. Si elige su propia configuración, debe conocer las opciones disponibles.



== Seleccione una licencia de Cloud Volumes ONTAP

Hay varias opciones de licencia disponibles para Cloud Volumes ONTAP. Cada opción le permite elegir un modelo de consumo que cumpla sus necesidades.

* link:concept-licensing.html["Obtenga información sobre las opciones de licencia para Cloud Volumes ONTAP"]
* link:task-set-up-licensing-aws.html["Aprenda a configurar las licencias"]




== Seleccione una región admitida

Cloud Volumes ONTAP se admite en la mayoría de las regiones de AWS. https://cloud.netapp.com/cloud-volumes-global-regions["Consulte la lista completa de las regiones admitidas"^].

Para poder crear y gestionar recursos en esas regiones, deben habilitarse las nuevas regiones de AWS. https://docs.aws.amazon.com/general/latest/gr/rande-manage.html["Aprenda a habilitar una región"^].



== Elija una instancia admitida

Cloud Volumes ONTAP admite varios tipos de instancia, según el tipo de licencia que elija.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["Configuraciones compatibles para Cloud Volumes ONTAP en AWS"^]



== Comprender los límites de almacenamiento

El límite de capacidad bruta de un sistema de Cloud Volumes ONTAP está relacionado con la licencia. Los límites adicionales afectan al tamaño de los agregados y los volúmenes. Debe conocer estos límites a medida que planifique la configuración.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-aws.html["Límites de almacenamiento para Cloud Volumes ONTAP en AWS"^]



== Configure el tamaño de su sistema en AWS

Configurar el tamaño de su sistema Cloud Volumes ONTAP puede ayudarle a cumplir los requisitos de rendimiento y capacidad. Al elegir un tipo de instancia, tipo de disco y tamaño de disco, debe tener en cuenta algunos puntos clave:

Tipo de instancia::
+
--
* Relacione los requisitos de carga de trabajo con el rendimiento máximo y las IOPS para cada tipo de instancia de EC2.
* Si varios usuarios escriben en el sistema al mismo tiempo, elija un tipo de instancia que tenga suficientes CPU para administrar las solicitudes.
* Si tiene una aplicación que está mayormente en lectura, elija un sistema con suficiente RAM.
+
** https://aws.amazon.com/ec2/instance-types/["Documentación de AWS: Tipos de instancias de Amazon EC2"^]
** https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html["Documentación de AWS: Instancias optimizadas para Amazon EBS"^]




--
Tipo de disco de EBS:: En líneas generales, las diferencias entre los tipos de discos de EBS son las siguientes. Para obtener más información acerca de los casos de uso para discos EBS, consulte http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["Documentación de AWS: Tipos de volúmenes de EBS"^].
+
--
* _Los discos SSD de uso general (gp3)_ son los SSD de menor coste que equilibran los costes y el rendimiento con una amplia variedad de cargas de trabajo. El rendimiento se define en términos de IOPS y rendimiento. Los discos gp3 son compatibles con Cloud Volumes ONTAP 9.7 y versiones posteriores.
+
Al seleccionar un disco gp3, BlueXP rellena los valores predeterminados de IOPS y rendimiento que proporcionan un rendimiento equivalente a un disco gp2 basado en el tamaño de disco seleccionado. Puede aumentar los valores para obtener un mejor rendimiento a un coste más alto, pero no apoyamos valores más bajos porque puede resultar en un rendimiento inferior. En resumen, cíñase a los valores predeterminados o aumentarlos. No los baje. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html#gp3-ebs-volume-type["Más información sobre los discos gp3 y su rendimiento"^].

+
Tenga en cuenta que Cloud Volumes ONTAP admite la función Amazon EBS Elastic Volumes con discos gp3. link:concept-aws-elastic-volumes.html["Obtenga más información sobre la compatibilidad con Elastic Volumes"].

* _SSD de uso general (gp2)_ los discos equilibran los costes y el rendimiento para una amplia gama de cargas de trabajo. El rendimiento se define en términos de IOPS.
* Los discos SSD (io1)_ de _IOPS aprovisionados están destinados a aplicaciones críticas que requieren el máximo rendimiento por un coste superior.
+
Tenga en cuenta que Cloud Volumes ONTAP es compatible con la función de volúmenes Elastic de Amazon EBS con discos io1. link:concept-aws-elastic-volumes.html["Obtenga más información sobre la compatibilidad con Elastic Volumes"].

* Los discos _HDD optimizados para rendimiento (st1)_ se utilizan para cargas de trabajo de acceso frecuente que requieren un rendimiento rápido y constante a un precio más reducido.
+

NOTE: No se recomienda la organización en niveles de los datos para el almacenamiento de objetos cuando se utilizan unidades HDD optimizadas para el rendimiento (st1).



--
Tamaño del disco de EBS:: Si elige una configuración que no sea compatible con link:concept-aws-elastic-volumes.html["Función Elastic Volumes de Amazon EBS"], Luego necesita elegir un tamaño de disco inicial al iniciar un sistema Cloud Volumes ONTAP. Después de eso, usted puede link:concept-storage-management.html["Deje que BlueXP gestione la capacidad de un sistema por usted"], pero si lo desea link:task-create-aggregates.html["cree agregados usted mismo"], tenga en cuenta lo siguiente:
+
--
* Todos los discos de un agregado deben tener el mismo tamaño.
* El rendimiento de los discos EBS está relacionado con el tamaño del disco. El tamaño determina la tasa de IOPS de base y la duración máxima de ráfaga para discos SSD, así como el rendimiento de línea base y de ráfaga para discos HDD.
* En última instancia, debe elegir el tamaño del disco que le proporcione el _rendimiento sostenido_ que necesita.
* Aunque elija discos más grandes (por ejemplo, seis discos de 4 TIB), es posible que no obtenga todas las IOPS porque la instancia de EC2 puede alcanzar su límite de ancho de banda.
+
Para obtener más información sobre el rendimiento del disco EBS, consulte http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["Documentación de AWS: Tipos de volúmenes de EBS"^].

+
Como se ha mencionado anteriormente, no es posible elegir un tamaño de disco para las configuraciones de Cloud Volumes ONTAP compatibles con la función Amazon EBS Elastic Volumes. link:concept-aws-elastic-volumes.html["Obtenga más información sobre la compatibilidad con Elastic Volumes"].



--




== Ver los discos del sistema predeterminados

Además del almacenamiento de los datos de usuario, BlueXP también adquiere almacenamiento en cloud para los datos del sistema Cloud Volumes ONTAP (datos de arranque, datos raíz, datos principales y NVRAM). Para fines de planificación, es posible que le ayude a revisar estos detalles antes de implementar Cloud Volumes ONTAP.

link:reference-default-configs.html#aws["Ver los discos predeterminados para los datos del sistema Cloud Volumes ONTAP en AWS"].


TIP: El conector también requiere un disco del sistema. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["Ver detalles sobre la configuración predeterminada del conector"^].



== Prepárese para implementar Cloud Volumes ONTAP en una entrada de AWS

Si tiene una publicación externa de AWS, puede implementar Cloud Volumes ONTAP en esa publicación seleccionando el VPC de salida en el asistente del entorno de trabajo. La experiencia es la misma que cualquier otro VPC que resida en AWS. Tenga en cuenta que primero deberá implementar un conector en su AWS Outpost.

Hay algunas limitaciones que señalar:

* Solo se admiten sistemas Cloud Volumes ONTAP de un solo nodo a. esta vez
* Las instancias de EC2 que se pueden utilizar con Cloud Volumes ONTAP está limitado a lo que hay disponible en su mensaje de salida
* Actualmente, solo se admiten las unidades SSD de uso general (gp2)




== Recopilar información de red

Al iniciar Cloud Volumes ONTAP en AWS, tiene que especificar detalles acerca de la red VPC. Puede utilizar una hoja de cálculo para recopilar la información del administrador.



=== Un único nodo o un par de alta disponibilidad en un único nodo de disponibilidad

[cols="30,70"]
|===
| Información de AWS | Su valor 


| Región |  


| VPC |  


| Subred |  


| Grupo de seguridad (si utiliza el suyo propio) |  
|===


=== Par DE ALTA DISPONIBILIDAD en varios AZs

[cols="30,70"]
|===
| Información de AWS | Su valor 


| Región |  


| VPC |  


| Grupo de seguridad (si utiliza el suyo propio) |  


| Nodo 1 zona de disponibilidad |  


| Subred nodo 1 |  


| Zona de disponibilidad del nodo 2 |  


| Subred del nodo 2 |  


| Zona de disponibilidad del mediador |  


| Subred del mediador |  


| Par clave para el mediador |  


| Dirección IP flotante para el puerto de gestión del clúster |  


| Dirección IP flotante para datos en el nodo 1 |  


| Dirección IP flotante para datos en el nodo 2 |  


| Tablas de rutas para direcciones IP flotantes |  
|===


== Elija una velocidad de escritura

BlueXP permite elegir una configuración de velocidad de escritura para Cloud Volumes ONTAP. Antes de elegir una velocidad de escritura, debe comprender las diferencias entre la configuración normal y la alta, así como los riesgos y recomendaciones cuando utilice la alta velocidad de escritura. link:concept-write-speed.html["Más información sobre la velocidad de escritura"].



== Seleccione un perfil de uso de volumen

ONTAP incluye varias funciones de eficiencia del almacenamiento que pueden reducir la cantidad total de almacenamiento que necesita. Al crear un volumen en BlueXP, puede elegir un perfil que habilite estas funciones o un perfil que las desactive. Debe obtener más información sobre estas funciones para ayudarle a decidir qué perfil utilizar.

Las funciones de eficiencia del almacenamiento de NetApp ofrecen las siguientes ventajas:

Aprovisionamiento ligero:: Presenta más almacenamiento lógico a hosts o usuarios del que realmente hay en el pool de almacenamiento físico. En lugar de asignar previamente espacio de almacenamiento, el espacio de almacenamiento se asigna de forma dinámica a cada volumen a medida que se escriben los datos.
Deduplicación:: Mejora la eficiencia al localizar bloques de datos idénticos y sustituirlos con referencias a un único bloque compartido. Esta técnica reduce los requisitos de capacidad de almacenamiento al eliminar los bloques de datos redundantes que se encuentran en un mismo volumen.
Compresión:: Reduce la capacidad física requerida para almacenar datos al comprimir los datos de un volumen en almacenamiento primario, secundario y de archivado.

