---
sidebar: sidebar 
permalink: task_dc_emc_vnxe.html 
keywords: data collector, VNXe, EMC 
summary: Configurar el recopilador de datos de VNXe. 
---
= Configurar el recopilador de datos de EMC VNXe
:allow-uri-read: 


[role="lead"]
El recopilador de datos VNXe de DELL EMC proporciona compatibilidad de inventario para las cabinas de almacenamiento unificado de VNXe. Actualmente Cloud Insights es compatible con los protocolos iSCSI y NAS.



== Requisitos

* El recopilador de datos de VNXe depende de la interfaz de línea de comandos; debe instalar Unisphere en la CLI de VNXe (uemcli.exe) en la unidad de adquisición donde reside el recopilador de datos de VNXe.
* uemcli.exe utiliza HTTPS como protocolo de transporte, de modo que la unidad de adquisición deberá poder iniciar conexiones HTTPS con el VNXe.
* La dirección IP o el nombre de dominio completo del dispositivo VNXe
* Debe tener al menos un usuario de sólo lectura para que lo utilice el recopilador de datos.
* Dirección IP del servidor de activación de soluciones de gestión.
* Se requiere HTTPS en el puerto 443
* El recopilador de datos de EMC VNXe proporciona compatibilidad con iSCSI y NAS para el inventario; se descubrirán volúmenes de Fibre Channel, pero Cloud Insights no informará sobre los puertos de almacenamiento, enmascaramiento ni asignación de FC.




== Terminología

Cloud Insights adquiere la siguiente información de inventario del recopilador de datos de VNXe. Para cada tipo de activo adquirido por Cloud Insights, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Disco | Disco 


| Cabina de almacenamiento | Reducida 


| Procesador | Nodo de almacenamiento 


| Pool de almacenamiento | Pool de almacenamiento 


| Información general sobre el bloque de iSCSI, VMFS de VMware | Share 


| Sistema remoto con replicación | Sincronización 


| Nodo iSCSI | Nodo de destino iSCSI 


| Iniciador iSCSI | Iniciador de destino iSCSI 
|===
Nota: Sólo se trata de asignaciones terminológicas comunes y es posible que no representen todos los casos de este origen de datos.



== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Almacenamiento VNXe | La dirección IP o el nombre de dominio completo del dispositivo VNXe 


| Nombre de usuario | Nombre de usuario del dispositivo VNXe 


| Contraseña | Contraseña del dispositivo VNXe 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | Intervalo entre sondeos de inventario. El valor predeterminado es 40 minutos 


| Puerto CLI | Puerto utilizado para la CLI de VNXe 


| Intervalo de sondeo de rendimiento (s) | El valor predeterminado es 300. 
|===


== Resolución de problemas

Algunas cosas para intentar si tiene problemas con este recopilador de datos:



==== Inventario

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| "No se pudo ejecutar la utilidad externa" con mensajes de error "no se pudo encontrar el uemcli ejecutable de Unisphere" | * Compruebe que la dirección IP, el nombre de usuario y la contraseña correctos * confirme que Unisphere CLI está instalado en la unidad de adquisición de Cloud Insights * confirme que el directorio de instalación de Unisphere CLI es correcto en la configuración de orígenes de datos * confirme que la IP del VNXe es correcta en la configuración del origen de datos. Desde la Unidad de adquisición de Cloud Insights, abra un CMD y cambie al directorio de instalación configurado: ${INSTALLDIR. Intente establecer una conexión con el dispositivo VNXe escribiendo: Uemcli -d <Your IP> -u <Your ID> /sys/general show 
|===
Puede encontrar información adicional en link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
