---
sidebar: sidebar 
permalink: task_isolate_root_volume.html 
summary: Al consultar la densidad de I/o alta, se desean excluir volúmenes raíz. 
keywords: NetApp, root volume, high I/O, 
---
= Si se asegura la generación de informes de densidad de I/o, se describen solo los volúmenes de datos
:allow-uri-read: 


[role="lead"]
El volumen raíz de NetApp contiene directorios y archivos de configuración para gestionar el sistema de almacenamiento. Al consultar la densidad de I/o alta, desea excluir estos volúmenes raíz.

Al supervisar su entorno, es más importante determinar qué volúmenes de datos internos producen números de densidad de I/o elevados. Para identificar exclusivamente los volúmenes de datos de forma precisa, debe aislar los volúmenes internos de NetApp de las consultas que utilice para supervisar la densidad de I/O.

En esta guía se describe cómo identificar fácilmente los agregados raíz de NetApp, aislarlos de los resultados de las consultas de volúmenes internos y crear reglas que excluyen los agregados raíz de NetApp nuevos a medida que se agregan al sistema. Las siguientes funciones de Insight se utilizan para garantizar que sus informes de densidad de I/o se obtienen de los volúmenes de datos internos:

* Se crea una consulta para identificar todos los agregados raíz de NetApp que supervisa Insight.
* Se asigna una anotación a cada uno de los agregados raíz de NetApp.
* Se crea una regla de anotación para aplicar la anotación a los nuevos agregados raíz de NetApp.


Los pasos de esta guía también se pueden aplicar a sistemas de almacenamiento de otro proveedor. Deberá identificar los volúmenes que contienen directorios y archivos de configuración para gestionar el sistema de almacenamiento y seguir pasos similares para excluir estos volúmenes.



== Crear una consulta para identificar los agregados raíz de NetApp en su entorno

Las consultas proporcionan una búsqueda a nivel granular basada en criterios seleccionados por el usuario. El uso de una consulta permite buscar volúmenes internos en el entorno que contienen el agregado raíz de NetApp.

. Pasos
. Cree una consulta para identificar los agregados raíz de NetApp en su entorno: Haga clic en *consultas > Nueva consulta > Seleccionar tipo de recurso* (?)
. Haga clic en *Grupo de almacenamiento*
. Escriba el nombre del agregado raíz
+
En este ejemplo se utiliza "aggr0" para el nombre. Al crear un agregado, sólo deben seguirse los siguientes requisitos para el nombre: .. Debe comenzar con una letra o un guión bajo (_). .. Puede contener solo letras, dígitos y guiones bajos. .. Puede tener 250 caracteres o menos. En la mayoría de los casos, el agregado es el nombre aggr0, aggr_0 o algo similar. Puede que requiera un proceso iterativo para identificar todos los agregados raíz de NetApp de su entorno.

. Haga clic en *Guardar* e introduzca un nombre para la nueva consulta.
+
Tal como se ha mencionado anteriormente, puede ser un proceso iterativo y requiere múltiples consultas para identificar todos los agregados raíz de NetApp.





== Cree una anotación para los volúmenes raíz devueltos por sus consultas

Las anotaciones son notas especializadas que asigna a sus activos, lo que le permite filtrar los activos por sus anotaciones. La anotación que cree se utilizará para identificar los agregados raíz de NetApp en su entorno y garantizar que no se incluyan en un informe específico.

.Antes de empezar
Debe haber identificado todos los agregados raíz que desea excluir del informe "Alta densidad de E/S".

.Pasos
. En el menú Cloud Insights, haga clic en *Administrar > Anotaciones*
. Haga clic en *Agregar*
+
.. Introduzca el nombre de la anotación: *RootAggr*
.. Introduzca una descripción de la anotación: *Eliminar agregado raíz del informe "Alta densidad de E/S"*
.. Introduzca el tipo de anotación: *Boolean*


. Haga clic en *Guardar*




== Cree una regla de anotación para automatizar la exclusión de agregados específicos del informe de densidad de E/S.

Como alternativa a la aplicación manual de anotaciones a activos individuales, puede aplicar anotaciones automáticamente a varios activos mediante reglas de anotación. Las reglas de anotación se basan en las consultas que se crean y cuando se ejecutan en el sistema agregan activos nuevos a los conjuntos de activos existentes. Cuando estos conjuntos de activos se excluyen de un informe, los nuevos activos también se excluyen automáticamente.

.Antes de empezar
Debe haber creado y guardado una consulta que identifique los agregados raíz de NetApp identificados en el entorno. . Pasos . En la barra de herramientas de Cloud Insights, haga clic en *Administrar > Reglas de anotación* . Haga clic en *Agregar*

+ el cuadro de diálogo Agregar regla aparece: .. En el cuadro Nombre , escriba un nombre único que describa la regla: *"RootAggrExclude"* .. Haga clic en Consulta y seleccione la consulta que Insight debe utilizar para aplicar la regla de anotación a: *"agregar0"* .. Haga clic en anotación y seleccione: *"raíz agg exclude"* .. Haga clic en *valor* e introduzca *Verdadero*
