---
sidebar: sidebar 
permalink: task_dc_emc_vnx_unified.html 
keywords: data collector, VNX, EMC, Dell 
summary: Configurar el recopilador de datos de VNX. 
---
= Configuración del recopilador de datos Dell EMC VNX Unified
:allow-uri-read: 


[role="lead"]
Para la configuración, el recopilador de datos Dell EMC VNX Unified (SSH) requiere la dirección IP de Control Station y un nombre de usuario y contraseña de sólo lectura.



== Terminología

Cloud Insights adquiere la siguiente información de inventario de este recopilador de datos. Para cada tipo de activo adquirido por Cloud Insights, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Disco | Disco 


| Carpeta de disco | Grupo de discos 


| Sistema de archivos | Volumen interno 


| Reducida | Reducida 


| Procesador de almacenamiento | Nodo de almacenamiento 


| Pool de almacenamiento, grupo RAID | Pool de almacenamiento 


| LUN | Volumen 


| Transmisor de datos | Controladora 


| Sistema de archivos montado en un transportador de datos | Recurso compartido de archivos 


| Exportaciones CIFS y NFS | Share 


| Volumen de disco | LUN back-end 
|===


== Requisitos

Para configurar el recopilador de datos de VNX (SSH) es necesario:

* Dirección IP y credenciales de VNX para Celerra Control Station.
* Nombre de usuario y contraseña de solo lectura.
* El recopilador de datos puede ejecutar comandos NaviCLI/NaviSecCLI contra la matriz de back-end utilizando los cabezales NAS del sistema operativo DART




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Dirección IP de VNX | Dirección IP o nombre de dominio completo de VNX Control Station 


| Nombre de usuario | Nombre de usuario de VNX Control Station 


| Contraseña | Contraseña de VNX Control Station 
|===


== configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | Intervalo entre sondeos de inventario. El valor predeterminado es 40 minutos. 


| Intervalo de sondeo de rendimiento (s). | Intervalo entre sondeos de rendimiento. El valor predeterminado es 300 segundos. 
|===


== Resolución de problemas

Se puede encontrar información adicional sobre este colector de datos en la link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
