---
sidebar: sidebar 
permalink: task_cs_user_management.html 
keywords: Cloud Secure, User, Login, account 
summary: Las cuentas de usuario de Cloud Secure se gestionan mediante la gestión de usuarios de Cloud Insights 
---
= Gestión de usuarios
:allow-uri-read: 


[role="lead"]
Las cuentas de usuario de Cloud Secure se gestionan mediante Cloud Insights.

Cloud Insights proporciona cuatro niveles de cuenta de usuario: Propietario de cuenta, administrador, usuario e invitado. A cada cuenta se le asignan niveles de permisos específicos. Una cuenta de usuario con privilegios de administrador puede crear o modificar usuarios y asignar a cada usuario uno de los siguientes roles de Cloud Secure:

|===


| Función | Acceso a Cloud Secure 


| Administrador | Puede realizar todas las funciones de Cloud Secure, incluidas las de Alertas, forenses, recopiladores de datos, directivas de respuesta automatizadas y API para Cloud Secure. Un administrador también puede invitar a otros usuarios, pero sólo puede asignar funciones de Cloud Secure. 


| Usuario | Puede ver y gestionar alertas y visualizar información forense. El rol de usuario puede cambiar el estado de alerta, añadir una nota, tomar instantáneas manualmente y restringir el acceso de usuario. 


| Invitado | Puede ver Alertas y Forensics. El rol de invitado no puede cambiar el estado de alerta, agregar una nota, tomar instantáneas manualmente o restringir el acceso de usuario. 
|===
.Pasos
. Inicie sesión en Cloud Secure
. En el menú, haga clic en *Administración > Administración de usuarios*
+
Se le reenviará a la página Gestión de usuarios de Cloud Insights.

. Seleccione el rol que desee para cada usuario.


Al agregar un nuevo usuario, solo tiene que seleccionar el rol que desee (normalmente Usuario o invitado).

Puede encontrar más información sobre las cuentas de usuario y las funciones en Cloud Insights link:https://docs.netapp.com/us-en/cloudinsights/concept_user_roles.html["Rol de usuario"] documentación.
