---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: Configurar el recopilador de datos de IBM SAN Volume Controller. 
---
= Configurar el recopilador de datos de IBM SAN Volume Controller
:allow-uri-read: 


[role="lead"]
El recopilador de datos de IBM SAN Volume Controller (SVC) recopila datos de inventario y rendimiento mediante SSH, lo que admite varios dispositivos que ejecutan el sistema operativo SVC.

La lista de dispositivos compatibles incluye modelos como SVC, v7000, v5000 y v3700. Consulte la matriz de compatibilidad de Cloud Insights para ver los modelos y versiones de firmware admitidos.



== Terminología

Cloud Insights adquiere la siguiente información de inventario del recopilador de datos IBM SVC. Para cada tipo de activo adquirido por Cloud Insights, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Unidad | Disco 


| Clúster | Reducida 


| Nodo | Nodo de almacenamiento 


| Grupo Mdisk | Pool de almacenamiento 


| VDisk | Volumen 


| Disco Mdisk | LUN y rutas de back-end 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



=== Requisitos de inventario

* Dirección IP de cada clúster SVC
* Puerto 22 disponible
* Nombre de usuario y contraseña de solo lectura




=== Requisitos de rendimiento

* Consola SVC, que es obligatoria para cualquier clúster SVC y necesaria para el paquete básico de la detección SVC.
* Las credenciales necesitarán el nivel de acceso administrativo solo para copiar los archivos de rendimiento de los nodos del clúster al nodo de configuración.
* Habilite la recopilación de datos conectando con SSH al clúster de SVC y ejecutando: _Svctask startstats -INTERVAL 1_
+
Nota: También puede activar la recopilación de datos mediante la interfaz de usuario de administración de SVC.





== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Direcciones IP del clúster | Direcciones IP o nombres de dominio completos del almacenamiento SVC 


| Nombre de usuario del inventario | Nombre de usuario de la CLI de SVC 


| Contraseña de inventario | Contraseña para la CLI de SVC 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | Intervalo entre sondeos de inventario. El valor predeterminado es 40 minutos. 


| Intervalo de sondeo de rendimiento (s) | Intervalo entre sondeos de rendimiento. El valor predeterminado es 300 segundos. 


| Para limpiar los archivos de estadísticas objeto de dumping | Seleccione esta casilla de verificación para limpiar los archivos de estadísticas que se han descargado 
|===


== Resolución de problemas

Algunas cosas para intentar si tiene problemas con este recopilador de datos:

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| Error: "No se puede iniciar el comando porque no se ejecutó en el nodo de configuración". | El comando debe ejecutarse en el nodo de configuración. 
|===
Algunas cosas para intentar si tiene problemas con este recopilador de datos:

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| Error: "No se puede iniciar el comando porque no se ejecutó en el nodo de configuración". | El comando debe ejecutarse en el nodo de configuración. 
|===
Se puede encontrar información adicional sobre este colector de datos en la link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
