---
sidebar: sidebar 
permalink: task_dc_hds_nas.html 
keywords: data collector, HDS HNAS, HDS NAS 
summary: 'Configurar el recopilador de datos HDS NAS (Hnas).' 
---
= Configuración del recopilador de datos Hitachi Vantara NAS
:allow-uri-read: 


[role="lead"]
El recopilador de datos de Hitachi Vantara NAS es un recopilador de datos de inventario y configuración que admite la detección de clústeres NAS de HDS. Cloud Insights admite la detección de recursos compartidos NFS y CIFS, sistemas de archivos (volúmenes internos) y abarcar (pools de almacenamiento).



== Terminología

Cloud Insights adquiere la siguiente información de inventario del recopilador de datos de Hnas. Para cada tipo de activo adquirido por Cloud Insights, se muestra la terminología más común utilizada para este activo. Al ver o solucionar problemas de este recopilador de datos, tenga en cuenta la siguiente terminología:

[cols="2*"]
|===
| Plazo del proveedor/modelo | Término de Cloud Insights 


| Nivel | Grupo de discos 


| Clúster | Reducida 


| Nodo | Nodo de almacenamiento 


| Capacidad de expansión | Pool de almacenamiento 


| Unidad del sistema | LUN de back-end 


| Sistema de archivos | Volumen interno 
|===
Nota: Sólo son asignaciones de terminología comunes y es posible que no representen todos los casos de este recopilador de datos.



== Requisitos

* Dirección IP del dispositivo
* Puerto 22, protocolo SSH
* Nombre de usuario y contraseña - nivel de privilegio: Supervisor
* Nota: Este recopilador de datos está basado en SSH, por lo que la unidad principal que la aloja debe ser capaz de iniciar sesiones SSH a TCP 22 en el propio Hnas o la unidad de administración de sistemas (SMU) a la que está conectado el clúster.




== Configuración

[cols="2*"]
|===
| Campo | Descripción 


| Host Hnas | Dirección IP o nombre de dominio completo del host de gestión Hnas 


| Nombre de usuario | Nombre de usuario de Hnas CLI 


| Contraseña | Contraseña usada para Hnas CLI 
|===


== Configuración avanzada

[cols="2*"]
|===
| Campo | Descripción 


| Intervalo de sondeo de inventario (mín.) | Intervalo entre sondeos de inventario. El valor predeterminado es 30 minutos. 
|===


== Resolución de problemas

Algunas cosas para intentar si tiene problemas con este recopilador de datos:



==== Inventario

[cols="2*"]
|===
| Problema: | Pruebe lo siguiente: 


| "Error al conectar" con mensajes de error "error al configurar el canal del shell:" o "error al abrir el canal del shell" | Probablemente causado por problemas de conectividad de red o SSH está mal configurado. Confirme la conexión con el cliente SSH alternativo 


| "Timeout" o "error al recuperar datos" con mensajes de error "Command: XXX ha agotado el tiempo de espera." | * Intente el comando con el cliente SSH alternativo * aumente el tiempo de espera 


| "Error al conectar " o "credenciales de inicio de sesión no válidas" con mensajes de error "no se pudo comunicar con el dispositivo:" | * Compruebe la dirección IP * Compruebe el nombre de usuario y la contraseña * confirme la conexión con el cliente SSH alternativo 
|===
Puede encontrar información adicional en link:concept_requesting_support.html["Soporte técnico"] o en la link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matriz de compatibilidad de recopilador de datos"].
